bash-4.2$ cd /c/cs458/lisp
bash-4.2$ lisp
This is SBCL 1.2.8-1.el7, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
* (load "sbclrc.lisp")


Welcome to Slade's LISP!
T
* (load "load_vote.lisp")

;; loading #P"/c/cs458/lisp/myload.fasl"
;; loading #P"/c/cs458/lisp/utils/sbcl.lisp"
WARNING:
   Specializing on the second argument to PRINT-OBJECT has unportable effects,
   and also interferes with precomputation of print functions for exceptional
   situations.
See also:
  The ANSI Standard, Function PRINT-OBJECT
;; loading #P"/c/cs458/lisp/load_utils.lisp"
;;; loading #P"/c/cs458/lisp/utils/generics.fasl"
;;; loading #P"/c/cs458/lisp/utils/copy.fasl"
;;; loading #P"/c/cs458/lisp/utils/ctime.fasl"
STYLE-WARNING:
   Implicitly creating new generic function COMMON-LISP-USER::ALL-THE-SLOTS.
;;; loading #P"/c/cs458/lisp/utils/io.fasl"
;;; loading #P"/c/cs458/lisp/utils/ionew.fasl"
;;; loading #P"/c/cs458/lisp/utils/macros.fasl"
;;; loading #P"/c/cs458/lisp/utils/object_hash.fasl"
;;; loading #P"/c/cs458/lisp/utils/props.fasl"
;;; loading #P"/c/cs458/lisp/utils/new_utils.fasl"
;;; loading #P"/c/cs458/lisp/utils/spell.fasl"
;;; loading #P"/c/cs458/lisp/utils/output.fasl"
STYLE-WARNING: OUT-SWITCH was previously defined as a macro.
STYLE-WARNING: redefining COMMON-LISP-USER::OUT-SWITCH in DEFUN
;;; loading #P"/c/cs458/lisp/utils/run-time.fasl"
;;; loading #P"/c/cs458/lisp/utils/date.fasl"
;;; loading #P"/c/cs458/lisp/utils/tables.fasl"
STYLE-WARNING:
   Implicitly creating new generic function COMMON-LISP-USER::MY-TABLE-WALK.
STYLE-WARNING:
   Implicitly creating new generic function COMMON-LISP-USER::MY-TABLE-ENTRY.
STYLE-WARNING:
   Implicitly creating new generic function COMMON-LISP-USER::MY-TABLE-SET.
;;; loading #P"/c/cs458/lisp/db/load_db.lisp"
;;;; loading #P"/c/cs458/lisp/db/specials_db.fasl"
;;;; loading #P"/c/cs458/lisp/db/db.fasl"
STYLE-WARNING:
   Implicitly creating new generic function COMMON-LISP-USER::SET-CURRENT-ITEMS.
STYLE-WARNING:
   Implicitly creating new generic function COMMON-LISP-USER::INIT-DB.
STYLE-WARNING:
   Implicitly creating new generic function COMMON-LISP-USER::INSERT-ITEM.
STYLE-WARNING:
   Implicitly creating new generic function COMMON-LISP-USER::REMOVE-ITEM.
STYLE-WARNING:
   Implicitly creating new generic function COMMON-LISP-USER::SORT-DB.
STYLE-WARNING:
   Implicitly creating new generic function COMMON-LISP-USER::NO-PP-FIELDS.
STYLE-WARNING:
   Implicitly creating new generic function
   COMMON-LISP-USER::NO-PRINT-READABLE-FIELDS.
;;;; loading #P"/c/cs458/lisp/db/copy.fasl"
;;;; loading #P"/c/cs458/lisp/db/db_cmds.fasl"
STYLE-WARNING:
   defining (*SPLIT-FILE-SIZE*) as a constant, even though the name follows
the usual naming convention (names like *FOO*) for special variables
;;;; loading #P"/c/cs458/lisp/db/db_cmds2.fasl"
;;;; loading #P"/c/cs458/lisp/db/edit.fasl"
;;;; loading #P"/c/cs458/lisp/db/note.fasl"
STYLE-WARNING:
   Implicitly creating new generic function COMMON-LISP-USER::INPUT-PROTOTYPE.
;;;; loading #P"/c/cs458/lisp/db/dbs/record.fasl"
STYLE-WARNING:
   Implicitly creating new generic function COMMON-LISP-USER::UPDATE-PROTOTYPE.
STYLE-WARNING: redefining COMMON-LISP-USER::ALL-THE-SLOTS in DEFGENERIC
STYLE-WARNING: redefining COMMON-LISP-USER::NO-PP-FIELDS in DEFGENERIC
STYLE-WARNING:
   redefining COMMON-LISP-USER::NO-PRINT-READABLE-FIELDS in DEFGENERIC
STYLE-WARNING: Implicitly creating new generic function COMMON-LISP-USER::OPEN?.
STYLE-WARNING:
   Implicitly creating new generic function COMMON-LISP-USER::CLOSED?.
STYLE-WARNING:
   Implicitly creating new generic function COMMON-LISP-USER::PENDING?.
STYLE-WARNING:
   Implicitly creating new generic function COMMON-LISP-USER::ACTIVE?.
STYLE-WARNING:
   Implicitly creating new generic function COMMON-LISP-USER::DELETED?.
;;;; loading #P"/c/cs458/lisp/db/dbs/task.fasl"
STYLE-WARNING:
   Implicitly creating new generic function COMMON-LISP-USER::PRINT-HC.
;;; loading #P"/c/cs458/lisp/pol/load_pol.lisp"
;;;; loading #P"/c/cs458/lisp/pol/specials_pol.fasl"
;;;; loading #P"/c/cs458/lisp/pol/utils.fasl"
;;;; loading #P"/c/cs458/lisp/pol/isa.fasl"
;;;; loading #P"/c/cs458/lisp/pol/sort.fasl"
;;;; loading #P"/c/cs458/lisp/pol/mypp.fasl"
STYLE-WARNING:
   Implicitly creating new generic function COMMON-LISP-USER::MY-PRETTY-PRINT.
;;;; loading #P"/c/cs458/lisp/pol/operations.fasl"
;;;; loading #P"/c/cs458/lisp/pol/remove.fasl"
;;;; loading #P"/c/cs458/lisp/pol/group.fasl"
STYLE-WARNING:
   Implicitly creating new generic function COMMON-LISP-USER::ENGLISH.
STYLE-WARNING:
   Implicitly creating new generic function COMMON-LISP-USER::SORT-KEY.
;;;; loading #P"/c/cs458/lisp/pol/issue.fasl"
;;;; loading #P"/c/cs458/lisp/pol/bill.fasl"
;;;; loading #P"/c/cs458/lisp/pol/member.fasl"
;;;; loading #P"/c/cs458/lisp/pol/strategy.fasl"
;;;; loading #P"/c/cs458/lisp/pol/stance.fasl"
;;;; loading #P"/c/cs458/lisp/pol/relation.fasl"
;;;; loading #P"/c/cs458/lisp/pol/decision.fasl"
;;;; loading #P"/c/cs458/lisp/pol/cg.fasl"
;;;; loading #P"/c/cs458/lisp/pol/strats.fasl"
;;;; loading #P"/c/cs458/lisp/pol/party-strat.fasl"
;;;; loading #P"/c/cs458/lisp/pol/shift.fasl"
;;;; loading #P"/c/cs458/lisp/pol/protocol.fasl"
;;;; loading #P"/c/cs458/lisp/pol/mem_anal.fasl"
;;;; loading #P"/c/cs458/lisp/pol/analyze.fasl"
;;;; loading #P"/c/cs458/lisp/pol/anal2.fasl"
;;;; loading #P"/c/cs458/lisp/pol/anal3.fasl"
;;;; loading #P"/c/cs458/lisp/pol/dd.fasl"
;;;; loading #P"/c/cs458/lisp/pol/parse.fasl"
;;;; loading #P"/c/cs458/lisp/pol/types.fasl"
;;;; loading #P"/c/cs458/lisp/gen/load_gen.lisp"
;;;;; loading #P"/c/cs458/lisp/gen/specials_gen.fasl"
;;;;; loading #P"/c/cs458/lisp/gen/clusters.fasl"
;;;;; loading #P"/c/cs458/lisp/gen/context.fasl"
STYLE-WARNING: Implicitly creating new generic function COMMON-LISP-USER::SAID?.
STYLE-WARNING:
   Implicitly creating new generic function COMMON-LISP-USER::USE-NOUN.
STYLE-WARNING:
   Implicitly creating new generic function COMMON-LISP-USER::SET-PRONOUN-COUNT.
STYLE-WARNING:
   Implicitly creating new generic function COMMON-LISP-USER::USE-PRONOUN?.
;;;;; loading #P"/c/cs458/lisp/gen/english.fasl"
STYLE-WARNING:
   Implicitly creating new generic function COMMON-LISP-USER::IS-ISSUE?.
;;;;; loading #P"/c/cs458/lisp/gen/gen_utils.fasl"
;;;;; loading #P"/c/cs458/lisp/gen/bill-english.fasl"
;;;;; loading #P"/c/cs458/lisp/gen/nouns.fasl"
;;;;; loading #P"/c/cs458/lisp/gen/np.fasl"
;;;;; loading #P"/c/cs458/lisp/gen/generics.fasl"
;;;;; loading #P"/c/cs458/lisp/gen/preamble.fasl"
;;;;; loading #P"/c/cs458/lisp/gen/rels.fasl"
;;;;; loading #P"/c/cs458/lisp/gen/verbs.fasl"
;;;;; loading #P"/c/cs458/lisp/gen/combine.fasl"
;;;;; loading #P"/c/cs458/lisp/gen/downside.fasl"
;;;;; loading #P"/c/cs458/lisp/gen/vp.fasl"
STYLE-WARNING:
   Implicitly creating new generic function COMMON-LISP-USER::ALL-THE-SYMBOLS.
;;;;; loading #P"/c/cs458/lisp/gen/test.fasl"
;;;;; loading #P"/c/cs458/lisp/gen/explain.fasl"

End of load_utils.lisp
The code is loaded.  Use (init-pol) to load the databases.
T
* (init-pol)

; Reading data base from file: /c/cs458/lisp/db/data/group
; loading #P"/c/cs458/lisp/db/data/group.load"
;; loading #P"/c/cs458/lisp/db/data/group0"
;; loading #P"/c/cs458/lisp/db/data/group1"
;; loading #P"/c/cs458/lisp/db/data/group2"
;; loading #P"/c/cs458/lisp/db/data/group3"
;; loading #P"/c/cs458/lisp/db/data/group4"
; loading #P"/c/cs458/lisp/db/data/group.upd"

; Reading data base from file: /c/cs458/lisp/db/data/bill
; loading #P"/c/cs458/lisp/db/data/bill.load"
;; loading #P"/c/cs458/lisp/db/data/bill0"
;; loading #P"/c/cs458/lisp/db/data/bill1"
;; loading #P"/c/cs458/lisp/db/data/bill2"
; loading #P"/c/cs458/lisp/db/data/bill.upd"

; Reading data base from file: /c/cs458/lisp/db/data/issue
; loading #P"/c/cs458/lisp/db/data/issue.load"
;; loading #P"/c/cs458/lisp/db/data/issue0"
;; loading #P"/c/cs458/lisp/db/data/issue1"
;; loading #P"/c/cs458/lisp/db/data/issue2"
;; loading #P"/c/cs458/lisp/db/data/issue3"
;; loading #P"/c/cs458/lisp/db/data/issue4"
;; loading #P"/c/cs458/lisp/db/data/issue5"
;; loading #P"/c/cs458/lisp/db/data/issue6"
; loading #P"/c/cs458/lisp/db/data/issue.upd"

; Reading data base from file: /c/cs458/lisp/db/data/member
; loading #P"/c/cs458/lisp/db/data/member.load"
;; loading #P"/c/cs458/lisp/db/data/member0"
;; loading #P"/c/cs458/lisp/db/data/member1"
; loading #P"/c/cs458/lisp/db/data/member.upd"

; Reading data base from file: /c/cs458/lisp/db/data/strategy
; loading #P"/c/cs458/lisp/db/data/strategy.load"
;; loading #P"/c/cs458/lisp/db/data/strategy"
;; loading #P"/c/cs458/lisp/db/data/strategy1"
; loading #P"/c/cs458/lisp/db/data/strategy.upd"
* (dbase member)

Initializing database system.
....MEMBER> help
HELP          print help information
?                         print command names
ACTIVE UNDELETE UNDEL     change status to active
ADD A                     add an item
ALIAS                     create a command synonym
AND                       selection conjunction
APPEND APP                append to field
COMPILE                   compile data file
COMPILE-DATE              date of last compilation
COMPLETED COMPLETE        flag current item as completed
COPY CP                   copy an entry
DELETE DEL                delete current item
DISPLAY DIS D             display current item
EDIT ED E                 edit a field
EXIT X                    save current updates and exit
EXPUNGE EXP               remove deleted items
GET G                     get old db
HEADERS HEADER HEAD H LS  print item headers
LOCK                      flag current item as locked
PENDING PEND P            change status to pending
PRINT                     print current db to file
PRINT-DATE                date of last printing
QUIT BYE Q                exit without saving current updates
SAVE S                    save current updates
SHOW-UPDATES UPDATES      show updated items
SORT                      sort items
SYN INDEX                 create an index synonym
CDB CD                    change to parent/child db
MKDB                      make child db at current item
MOVE MV                   move current item to given db
UNDO U                    undo last command
NOTES NOTE                update the Notes field
NAME                      update the Name field
SHORT ENGLISH-SHORT       update the English-Short field
FIRST FNAME               update the Fname field
LAST LNAME                update the Lname field
VOTES VOTE                update the Votes field
NEW-VOTES                 update the New-Votes field
PARTY                     update the Party field
DISTRICT                  update the District field
STANCES                   update the Stances field
REL-STANCES               update the Pro-Rel-Stances field
STANCE-SORT-KEY           update the Stance-Sort-Key field
CREDO                     update the Credo field
GENDER                    update the Gender field
RELS RELATION RELATIONS   update the Relations field
TERM-START ELECTED        update the Term-Start field
TERM-END DEPARTED         update the Term-End field
ISSUES ISSUE              update the Issues field
GROUP GROUPS              update the Groups field
COMMITTEES COMMITTEE      update the Committees field
DATE-CLOSED CLOSED        update the Date-Closed field
DATE-OPEN OPEN            update the Date-Open field
REMARKS TEXT              update the Remarks field
STATUS ST                 update the Status field
SUBJECT SUBJ              update the Subject field
KEYWORDS KEYS             update the Keywords field
DB                        update the Db field

aliases:
AR                  APPEND RELATIONS 
ER                  EDIT RELATIONS 
ANV                 APPEND NEW-VOTES 
HL                  HEADERS LAST 
HC                  HEADERS CURRENT 
AC                  APPEND COMMITTEES 
AV                  APPEND VOTES 
SHOW                DISPLAY 
....MEMBER> headers

      0   Daniel Kahikina Akaka         (DEM) HI-2   (1976-1990)
      1   Les AuCoin                    (DEM) OR-1   (1974- )
      2   Druie Douglas Barnard         (DEM) GA-10  (1976- )
      3   Charles Edward Bennett        (DEM) FL-3   (1948- )
      4   Corinne Claiborne Lindy Boggs  (DEM) LA-2  (1973-1990)
      5   Beverly Butcher Byron         (DEM) MD-6   (1978- )
      6   Thomas R. Carper              (DEM) DE-AL  (1982- )
      7   William Lacy Clay             (DEM) MO-1   (1968- )
      8   Silvio Ottavio Conte          (REP) MA-1   (1958-1990)
      9   James A. Courter              (REP) NJ-12  (1978-1990)
      10  Larry E. Craig                (REP) ID-1   (1980-1990)
      11  William Louis Dickinson       (REP) AL-2   (1964- )
      12  John D. Dingell               (DEM) MI-16  (1955- )
      13  Byron Leslie Dorgan           (DEM) ND-AL  (1980- )
      14  Glenn English                 (DEM) OK-6   (1974- )
      15  James J. Florio               (DEM) NJ-1   (1974-1990)
      16  Thomas S. Foley               (DEM) WA-5   (1964- )
      17  Bill Frenzel                  (REP) MN-3   (1970-1990)
      18  Samuel Gejdenson              (DEM) CT-2   (1980- )
      19  Richard A. Gephardt           (DEM) MO-3   (1976- )
      20  Newt Gingrich                 (REP) GA-6   (1978- )
      21  Daniel Robert Glickman        (DEM) KS-4   (1976- )
      22  Henry B. Gonzalez             (DEM) TX-20  (1961- )
      23  William H. Gray               (DEM) PA-2   (1978- )
      24  Lee H. Hamilton               (DEM) IN-9   (1964- )
      25  John Paul Hammerschmidt       (REP) AR-3   (1966- )
      26  James V. Hansen               (REP) UT-1   (1980- )
      27  Augustus F. Hawkins           (DEM) CA-29  (1962-1990)
      28  Frank Horton                  (REP) NY-29  (1962- )
      29  Nancy Lee Johnson             (REP) CT-6   (1982- )
      30  Timothy Peter Johnson         (DEM) SD-AL  (1986- )
      31  Walter Berman Jones           (DEM) NC-1   (1966- )
      32  Marcy Kaptur                  (DEM) OH-9   (1982- )
      33  Robert William Kastenmeier    (DEM) WI-2   (1958-1990)
      34  Barbara Kennelly              (DEM) CT-1   (1982- )
      35  Mickey Leland                 (DEM) TX-18  (1978-1989)
      36  Ronald Charles Marlenee       (REP) MT-2   (1976- )
      37  Joseph M. McDade              (REP) PA-10  (1962- )
      38  Robert H. Michel              (REP) IL-18  (1956- )
      39  Clarence E. Miller            (REP) OH-10  (1966- )
      40  Bruce A. Morrison             (DEM) CT-3   (1982-1990)
      41  William Huston Natcher        (DEM) KY-2   (1953- )
      42  Stan Parris                   (REP) VA-8   (1980-1990)
      43  Claude Denson Pepper          (DEM) FL-18  (1962-1989)
      44  James Henry Quillen           (REP) TN-1   (1962- )
      45  Nick Joe Rahall               (DEM) WV-4   (1976- )
      46  Robert A. Roe                 (DEM) NJ-8   (1969- )
      47  Dan Rostenkowski              (DEM) IL-8   (1958- )
      48  John Grosvenor Rowland        (REP) CT-5   (1984-1990)
      49  Claudine Schneider            (REP) RI-2   (1980-1990)
      50  Patricia Scott Schroeder      (DEM) CO-1   (1972- )
      51  Christopher Shays             (REP) CT-4   (1987- )
      52  Joseph Richard Skeen          (REP) NM-2   (1980- )
      53  Neal Edward Smith             (DEM) IA-4   (1958- )
      54  Peter Smith                   (REP) VT-AL  (1988-1990)
      55  Robert Clinton Smith          (REP) NH-1   (1984-1990)
      56  Virginia Dodd Smith           (REP) NE-3   (1974-1990)
      57  Olympia J. Snowe              (REP) ME-2   (1978- )
      58  Floyd D. Spence               (REP) SC-2   (1970- )
      59  Louis Stokes                  (DEM) OH-21  (1968- )
      60  Michael L. Synar              (DEM) OK-2   (1978- )
      61  Esteban Edward Torres         (DEM) CA-34  (1982- )
      62  Robert G. Torricelli          (DEM) NJ-9   (1982- )
      63  Morris K. Udall               (DEM) AZ-2   (1961-1991)
      64  Barbara F. Vucanovich         (REP) NV-2   (1982- )
      65  Jamie L. Whitten              (DEM) MS-1   (1941- )
  *   66  Don Young                     (REP) AK-AL  (1973- )
....MEMBER> hc

  *   66  Don Young                     (REP) AK-AL  (1973- )
....MEMBER> display

Name:          Don Young
Fname:         DON
Lname:         YOUNG
Votes:         ((DEFENSE-AUTHORIZATION AGN) (SPACE-STATION AGN)
                (CIVIL-RIGHTS-RESTORATION-ACT FOR) (REFLAGGING-SHIPS --)
                (HANDGUN-CONTROL FOR) (CONTRA-AID2 AGN) (STAR-WARS AGN)
                (HOME-HEALTH-CARE AGN) (AIDS AGN) (LIMIT-IMPORTS FOR)
                (CAP-TAX-CUT AGN) (EXTEND-SS-BENEFIT AGN)
                (ESTAB-DOM-CONTENT FOR) (BAR-IMM-AMNESTY FOR)
                (OK-SCHOOL-PRAY FOR) (LIMIT-ABORTIONS FOR) (APPROVE-ERA FOR)
                (PASS-IMM-REFORM AGN) (CANCEL-MX-MISSILE AGN)
                (HALT-AID-TO-CONTRAS AGN) (INCR-AID-TO-EL-SAL FOR)
                (SUPP-NUCLEAR-FREEZE FOR) (CAP-GAINS-CUT AGN)
                (LMT-CLN-WATER-ACT AGN) (RPL-TOBAC-SUB AGN)
                (GRM-RDMN-DEF-RED FOR) (BAN-POLYGRAPH FOR)
                (RETAIN-GUN-CONTROL AGN) (CONTRA-AID FOR) (LMT-TEXT-IMP AGN)
                (LIMIT-SDI AGN) (AID-ANGOLA-REB FOR) (TAX-REFORM AGN)
                (S-AFRICA-SANC FOR) (IMMIG-REFORM AGN) (CHILD-CARE AGN)
                (FLAG-BURNING FOR) (BRADY-BILL AGN))
Relations:     (#{Relation (0) [B:CON] ADA (MEMBER:MEMBER.1024)}
                #{Relation (1) [B:CON] ACLU (MEMBER:MEMBER.1024)}
                #{Relation (2) [C:CON] COPE (MEMBER:MEMBER.1024)}
                #{Relation (3) [B:CON] CFA (MEMBER:MEMBER.1024)}
                #{Relation (4) [B:CON] LCV (MEMBER:MEMBER.1024)}
                #{Relation (5) [C:PRO] ACU (MEMBER:MEMBER.1024)}
                #{Relation (6) [C:CON] NTU (MEMBER:MEMBER.1024)}
                #{Relation (7) [A:PRO] NSI (MEMBER:MEMBER.1024)}
                #{Relation (8) [C:PRO] COC (MEMBER:MEMBER.1024)}
                #{Relation (9) [C:CON] CEI (MEMBER:MEMBER.1024)}
                #{Relation (10) [C:CON] DEMOCRATS (MEMBER:MEMBER.1024)}
                #{Relation (11) [C:PRO] REPUBLICANS (MEMBER:MEMBER.1024)}
                #{Relation (12) [C:PRO] COUNTRY (MEMBER:MEMBER.1024)})
District:      AK-AL
Term-Start:    1973
Party:         REP
Committees:    (HOUSE-INTERIOR)
Status:        Active
Date-Open:     Tuesday, September 19, 1989
Symbol:        MEMBER.1024
Don Young is a staunch defender of the sound defense posture of
the NSI.  He is an opponent of the ACLU's radical and subversive
posture, the Consumer Federation of America, the League of Conservation
Voters, and moreover the left-wing pinko ADA.  He is in favor
of Republicans, the US Chamber of Commerce, the American Conservative
Union, and the country as a whole.  Young objects to members of
the Democratic party, the National Taxpayers Union, the Competitive
Enterprise Institute, in addition to the Committee on Political
Education of the AFL-CIO.  
....MEMBER> cd issue

....ISSUE> help
HELP           print help information
?                         print command names
ACTIVE UNDELETE UNDEL     change status to active
ADD A                     add an item
ALIAS                     create a command synonym
AND                       selection conjunction
APPEND APP                append to field
COMPILE                   compile data file
COMPILE-DATE              date of last compilation
COMPLETED COMPLETE        flag current item as completed
COPY CP                   copy an entry
DELETE DEL                delete current item
DISPLAY DIS D             display current item
EDIT ED E                 edit a field
EXIT X                    save current updates and exit
EXPUNGE EXP               remove deleted items
GET G                     get old db
HEADERS HEADER HEAD H LS  print item headers
LOCK                      flag current item as locked
PENDING PEND P            change status to pending
PRINT                     print current db to file
PRINT-DATE                date of last printing
QUIT BYE Q                exit without saving current updates
SAVE S                    save current updates
SHOW-UPDATES UPDATES      show updated items
SORT                      sort items
SYN INDEX                 create an index synonym
CDB CD                    change to parent/child db
MKDB                      make child db at current item
MOVE MV                   move current item to given db
UNDO U                    undo last command
NOTES NOTE                update the Notes field
NAME                      update the Name field
SYNONYMS SYNONYM NAMES    update the Synonyms field
TYPE                      update the Type field
ISA                       update the Isa field
GROUPS GROUP              update the Groups field
OPPOSITE                  update the Opposite field
NORM NORMS                update the Norm field
PRO-STANCES PRO-S         update the Pro-Stances field
CON-STANCES CON-S         update the Con-Stances field
ENGLISH ENG               update the English field
ENGLISH-SHORT SHORT       update the English-Short field
PRO-ENGLISH PRO-E         update the Pro-English field
CON-ENGLISH CON-E         update the Con-English field
FRENCH                    update the French field
FRENCH-SHORT              update the French-Short field
PRO-FRENCH PRO-F          update the Pro-French field
CON-FRENCH CON-F          update the Con-French field
NUMBER                    update the Number field
POLARITY POLAR            update the Polarity field

aliases:
DAY-CARE            CHILD-CARE 
EDITC               EDIT CON-STANCES 
EDITP               EDIT PRO-STANCES 
CONS                CON-STANCES 
PROS                PRO-STANCES 
ACON                APPEND CON-STANCES 
APRO                APPEND PRO-STANCES 
CON-STANCE          CON-STANCES 
PRO-STANCE          PRO-STANCES 
HL                  HEADERS LAST 
HEADER              HEADERS 
HC                  HEADERS CURRENT 
....ISSUE> headers

      0   AIDS                                    +B
      1   Abortion                                +C
      2   Acid Rain Control                       +C(ACID-RAIN-CONTROL)
      3   Affirmative Action                      +C(AFFIRMATIVE-ACTION)
      4   Africa                        FOREIGN     
      5   Age Discrimination            PROBLEM   -C(AGE-DISCRIMINATION)
      6   Agricultural subsidies                  -C(FARM AGRICULTURE)
      7   Aid to Nicaraguan Contras                 (CONTRA-AID CONTRAS)
      8   Air Pollution Control         POLICY    +C(CLEAN-AIR
                                                     AIR-POLLUTION-CONTROL)
      9   Aircraft Carriers                         (CARRIERS)
      10  Angola                        FOREIGN     
      11  Angola Rebels                 GROUP       (ANGOLA-REBELS)
      12  Anti-Ballistic Missile Treaty           +C(ABM)
      13  Anti-Semitism                           -B
      14  Anti-trust reform                       +C(ANTI-TRUST-REFORM)
      15  Apartheid                     PROBLEM   -B
      16  Arab-Israeli Conflict                   +B(ARAB-ISRAELI-CONFLICT)
      17  Armored Divisions                         (ARMORED-DIVISIONS TANKS)
      18  Arms Control                            +B(ARMS-CONTROL)
      19  B-1 Bomber                                (B-1 B1)
      20  Balance of Power              PRINCIPLE +B(BALANCE-OF-POWER)
      21  Balanced Budget                         +C(BALANCED-BUDGET)
      22  Banking industry              GROUP       (BANKING)
      23  Birth Control                 RIGHT     +C(BIRTH-CONTROL)
      24  Bond Taxation                           -C(BOND-TAXATION)
      25  Bork Appointment              NOMINATION   (BORK)
      26  Budget Freeze                 PROPOSAL    (BUDGET-FREEZE FREEZE)
      27  Business                      GROUP       (INDUSTRY)
      28  Cabinet Level Veterans Department PROPOSAL +C(CABINET-VETERANS)
      29  Campaign Finance Reform                 +C(CAMPAIGN-FINANCE)
      30  Cancer research                         +B(CANCER)
      31  Capital Punishment            PRINCIPLE +C(CAPITAL-PUNISHMENT
                                                     DEATH-PENALTY)
      32  Capital gains tax cut         ECONOMIC  +C(CAPITAL-GAINS-TAX-CUT)
      33  Catastrophic Health Costs     PROGRAM   +C(CATASTROPHIC-HEALTH-COSTS)
      34  Central America               FOREIGN     (CENTRAL-AMERICA)
      35  Central American Peace Plan   FOREIGN   +C(CENTRAL-AMERICAN-PEACE-PLAN)
      36  Chemical Weapons                        -C(CHEMICAL-WEAPONS)
      37  Child Care                    PROPOSAL  +B(CHILDCARE DAYCARE
                                                     CHILD-CARE)
      38  Civil Liberties               PRINCIPLE   (CIVIL-LIBERTIES)
      39  Civil Rights                  CAUSE     +C(CIVIL-RIGHTS)
      40  Clinch River breeder reactor  PROPOSAL    (CLINCH-RIVER)
      41  Cold War                      PROBLEM   -C(COLD-WAR)
      42  Compassion                    PRINCIPLE +B(MERCY COMPASSION)
      43  Constitution                  PRINCIPLE +B(CONSTITUTION
                                                     BILL-OF-RIGHTS)
      44  Constructive Engagement       POLICY      (CONSTRUCTIVE-ENGAGEMENT)
      45  Consumer Protection           CAUSE     +C(CONSUMER)
      46  Conventional Defense                    +C(CONVENTIONAL-DEFENSE)
      47  Creationism                               
      48  Cruise Missile                            (CRUISE)
      49  Cut taxes                     ECONOMIC  +B(CUT-TAXES TAX-CUTS)
      50  D-5 Missile                               (D5)
      51  Defense Spending                        +C(DEFENSE MILITARY
                                                     DEFENSE-SPENDING)
      52  Deficit                                 -C(BUDGET-DEFICIT DEFICIT)
      53  Democracy                     PRINCIPLE +B
      54  Deregulation                  PRINCIPLE +C
      55  Diplomatic efforts                      +C(DIPLOMACY
                                                     DIPLOMATIC-EFFORTS)
      56  Domestic Policy                           (DOMESTIC)
      57  Drug Enforcement              POLICY    +B(DRUG-ENFORCEMENT DRUGS)
      58  East-West Relationships       FOREIGN     (EAST-WEST)
      59  Economic Policy                         +B(ECONOMIC ECONOMY)
      60  Education Policy              POLICY      (EDUCATION)
      61  El Salvador                   FOREIGN     (EL-SALVADOR)
      62  Elderly                       GROUP     +B
      63  Election Reform               REFORM    +C(ELECTION-REFORM)
      64  Elections                     PRINCIPLE +B(ELECTION)
      65  End of Hostilities            OPPORTUNITY +C(END-OF-HOSTILITIES
                                                       CEASEFIRE)
      66  Energy Conservation                     +C(ENERGY)
      67  Environmental Protection                +C(ENVIRONMENT ECOLOGY
                                                     CONSERVATION)
      68  Equal Rights Amendment        PROPOSAL    (ERA)
      69  Equality                      PRINCIPLE +B(EQUALITY EQUITY)
      70  Euromissile Treaty                      +C(INF-TREATY)
      71  Fair Trial                    PRINCIPLE +B(FAIR-TRIAL DUE-PROCESS)
      72  Fairness                      PRINCIPLE +C
      73  Family values                 SOCIAL    +C(FAMILY FAMILY-VALUES)
      74  Federal programs              ISSUE       (FEDERAL-PROGRAMS)
      75  Fiscal responsibility         PRINCIPLE +B(FISCAL-RESPONSIBILITY)
      76  Flag Burning                  RIGHT     -C(FLAG-BURNING)
      77  Food Stamps                             +C(FOOD-STAMPS)
      78  Foreign Policy                          +B(FOREIGN)
      79  Foreign Relations Organizations GROUP     (FOREIGN-ORG)
      80  Free Enterprise               PRINCIPLE +C(FREE-ENTERPRISE CAPITALISM
                                                     FREE-MARKET)
      81  Free Trade                    PRINCIPLE   (FREE-TRADE)
      82  Freedom                       PRINCIPLE +A(FREEDOM LIBERTY)
      83  Freedom of Speech             RIGHT     +B(FREE-SPEECH)
      84  Freedom of the Press          RIGHT     +C(FREEDOM-OF-THE-PRESS)
      85  Full employment                         +B(JOBS EMPLOYMENT)
      86  Future of the Country                   +B(FUTURE)
      87  Gay Rights                              -C(GAY-RIGHTS)
      88  Generic Issue                             (ISSUE ISSUES)
      89  Government Spending                     -C(SPENDING)
      90  Government waste control                +B(WASTE)
      91  Gun Control                   CAUSE     +C(GUN-CONTROL)
      92  Handicapped                   GROUP     +C
      93  Hard work                     PRINCIPLE +B(HARD-WORK)
      94  Health Care                   CAUSE     +B(HEALTH-CARE HEALTH)
      95  Help wealthy citizens         ECONOMIC  -C(HELP-WEALTHY)
      96  Homelessness                  GROUP     +C(HOMELESS HOMELESSNESS)
      97  Honesty                       PRINCIPLE +B(HONESTY)
      98  Housing                                 +C
      99  Human Rights                  PRINCIPLE +C(HUMAN-RIGHTS)
      100  Human values                 ISSUE     +A(HUMAN-VALUES VALUES VALUE
                                                     SOCIAL-VALUE)
      101  Humanitarianism              PRINCIPLE +B
      102  Hunger                                 +B
      103  Idealism                     PRINCIPLE +C
      104  Immigration Reform           REFORM      (IMMIGRATION
                                                     IMMIGRATION-REFORM)
      105  Inflation reduction                    +B(INFLATION)
      106  Integrity                    PRINCIPLE +B
      107  Intelligence Operations                  (INTELLIGENCE)
      108  Isolationism                 POLICY    -C
      109  Israel                       FOREIGN   +C
      110  Jewish Refusniks / Soviet Jews GROUP   +C(SOVIET-JEWS)
      111  Job Protection               ECONOMIC  +C(JOB-PROTECTION)
      112  Judicial Appointments                  +C(JUDGESHIP)
      113  Justice                      PRINCIPLE +A
      114  Labor Issues                 GROUP       (LABOR)
      115  Latin America                FOREIGN     (LATIN-AMERICA)
      116  Law and Order                PRINCIPLE +B(LAW-AND-ORDER
                                                     LAW-ENFORCEMENT CRIME)
      117  Legal Services               PROGRAM     (LEGAL-SERVICES)
      118  Limited Judicial Review of Veterans Compensation Cases POLICY   (VETERANS-JUDICIAL-REVIEW)
      119  MIAs                                   +C
      120  MX Missiles                              (MX MX-MISSILE)
      121  Manion Appointment           NOMINATION   (MANION)
      122  Medicare and Medicaid                  +B(MEDICARE MEDICAID)
      123  Mexico                       FOREIGN   +C
      124  Middle East                            +B(MID-EAST MIDDLE-EAST)
      125  Midgetman Missile                        (MIDGETMAN)
      126  Military Procurement                   +C(MILITARY-PROCUREMENT)
      127  Military Solution            POLICY    -C(MILITARY-SOLUTION)
      128  Minimum wage                           +C(MINIMUM-WAGE)
      129  National Security            PRINCIPLE +B(NATIONAL-SECURITY SECURITY)
      130  National autonomy            PRINCIPLE +C(NATIONAL-AUTONOMY)
      131  Nationalism                  PRINCIPLE +B
      132  Nicaragua                    FOREIGN     
      133  Non-involvement              POLICY    +C
      134  North Atlantic Treaty Organization GROUP +C(NATO)
      135  North-South Relationships              +C(THIRD-WORLD NORTH-SOUTH
                                                     RICH-POOR)
      136  Nuclear Freeze               PROPOSAL  +C(NUCLEAR-FREEZE)
      137  Nuclear Test Ban                       +C(NUCLEAR-TEST-BAN)
      138  Nuclear Weapons                        -C(NUCLEAR-WEAPON)
      139  Occupational Safety and Health         +C(SAFETY OSHA)
      140  Open Housing                 PRINCIPLE +C(OPEN-HOUSING)
      141  Opposition to communism                +B(COMMUNISM)
      142  POWs                         GROUP     +B
      143  Palestinian Homeland                   +C(PALESTINIAN-HOMELAND)
      144  Panama                       FOREIGN   +C
      145  Patriotism                   PRINCIPLE +B
      146  Peace                        PRINCIPLE +B(PEACE)
      147  Persian Gulf Policy                    +C(PERSIAN-GULF)
      148  Philippines                  FOREIGN   +C
      149  Plant Closing                PROPOSAL    (PLANT-CLOSING)
      150  Pledge of Allegiance                   +B(PLEDGE)
      151  Poland                       FOREIGN   +C
      152  Poverty Programs                       +C(POVERTY)
      153  Pragmatism                   PRINCIPLE   
      154  President                              +C
      155  President Bush                         +C(BUSH)
      156  President Reagan                       +C(REAGAN)
      157  Prevention of Smoking                  +C(SMOKING-BAN
                                                     SMOKING-WARNINGS)
      158  Prison and Corrections       REFORM    +B(PRISON)
      159  Prisoner Furloughs           POLICY    -C(FURLOUGHS)
      160  Privacy Protection           PRINCIPLE +C(PRIVACY)
      161  Privatization                          -C
      162  Progress                     PRINCIPLE   
      163  Prosperity                   ECONOMIC  +B
      164  Public TV and radio          PROGRAM   +C(PUBLIC-TV PUBLIC-RADIO)
      165  Public Works                             (PUBLIC-WORKS)
      166  Racism                       PROBLEM   -C
      167  Regulation                   PRINCIPLE   (REGULATION)
      168  Religious freedom            PRINCIPLE +A(RELIGION RELIGIOUS-FREEDOM)
      169  Responsibility               PRINCIPLE +B
      170  Retribution                  PRINCIPLE +C
      171  Right to an Education        RIGHT     +C(EDUCATION-RIGHTS)
      172  Rural Electrification        PROGRAM   +C(RURAL-ELECTRIC)
      173  School Bussing               POLICY    -C(BUSSING)
      174  School Desegregation         POLICY    +C(DESEGREGATION)
      175  School Prayer                PROPOSAL  +C(PRAYER)
      176  Self Determination           RIGHT     +B(SELF-DETERMINATION)
      177  Separation of church and state PRINCIPLE +C(CHURCH-AND-STATE)
      178  Social Policy                            (SOCIAL)
      179  Social Security                        +B(SOCIAL-SECURITY)
      180  South Africa                           -C(SOUTH-AFRICA)
      181  South America                FOREIGN   +C(SOUTH-AMERICA)
      182  Soviet Union                 FOREIGN   +C(USSR RUSSIA)
      183  Space Exploration            PROGRAM   +C(SPACE)
      184  States Rights                PRINCIPLE +C(STATES-RIGHTS)
      185  Stealth Bomber                           (STEALTH)
      186  Stimulate investment         ECONOMIC  +C(SPUR-INVESTMENT)
      187  Strategic Defense Initiative PROGRAM   +C(SDI)
      188  Student loans                PROGRAM   +C(STUDENT-LOANS)
      189  Superfund                              +C(SUPERFUND)
      190  Taiwan                       FOREIGN   +C(CHINA TAIWAN)
      191  Tax Reform                             +C(TAX-REFORM)
      192  Taxes                        POLICY    -B
      193  Textile Industry             GROUP       (TEXTILE-INDUSTRY TEXTILES)
      194  Third World Debt                       +C(THIRD-WORLD-DEBT)
      195  Tobacco Price Supports                   (TOBACCO-PRICE-SUPPORTS)
      196  Totalitarianism              PRINCIPLE -B
      197  Tower Nomination             NOMINATION   (TOWER)
      198  Toxic waste cleanup                    +C(TOXIC-WASTE)
      199  Trade                                  +C
      200  Trade Deficit Reduction                +C(TRADE-DEFICIT)
      201  Trade Restrictions           POLICY      (TRADE-RESTRICTIONS)
      202  Tradition                    PRINCIPLE +C
      203  Transportation                           
      204  Trident 2 Submarine                      (TRIDENT2
                                                     TRIDENT-II-MISSILE)
      205  Unemployment                           +C(UNEMPLOYMENT)
      206  Unemployment insurance       PROGRAM   +C(UNEMPLOYMENT-INSURANCE)
      207  United Nations               FOREIGN   +C(UN UNITED-NATIONS)
      208  Urban Renewal                          +C(SLUM CLEARANCE URBAN
                                                     RENEWAL URBAN-RENEWAL)
      209  Veterans Affairs             GROUP     +C(VETERANS VETERANS-BENEFITS)
      210  Vietnam Trade Relations                  (VIETNAM-TRADE-RELATIONS)
      211  Voting Rights                PRINCIPLE +C(VOTING-RIGHTS)
      212  Warsaw Pact Nations          FOREIGN     (WARSAW-PACT IRON-CURTAIN)
      213  Water Pollution Control      PROGRAM   +C(CLEAN-WATER
                                                     WATER-POLLUTION-CONTROL)
      214  Weapons                                +C(WEAPON WEAPONS)
      215  Whistle Blowers              GROUP     +C(WHISTLE-BLOWERS)
  *   216  Women's Rights                         +C(WOMENS-RIGHTS)
....ISSUE> hc

  *   216  Women's Rights                         +C(WOMENS-RIGHTS)
....ISSUE> display

Name:          Women's Rights
Synonyms:      (WOMENS-RIGHTS)
Isa:           (CIVIL-RIGHTS)
Polarity:      Support federal efforts to end sex discrimination
English:       women's civil rights
English-Short:  women's rights
Pro-English:   the legitimate rights and concerns of women
Con-English:   radical feminist positions
Groups:        (NOW WOMEN)
Pro-Stances:   (#{Stance (13) [B:PRO] PRIVACY (ISSUE:WOMENS-RIGHTS)}
                #{Stance (14) [B:PRO] ABORTION (ISSUE:WOMENS-RIGHTS)}
                #{Stance (15) [B:PRO] EQUALITY (ISSUE:WOMENS-RIGHTS)}
                #{Stance (16) [B:PRO] FAIRNESS (ISSUE:WOMENS-RIGHTS)}
                #{Stance (17) [B:PRO] PROGRESS (ISSUE:WOMENS-RIGHTS)})
Con-Stances:   (#{Stance (18) [C:PRO] FAMILY (ISSUE:WOMENS-RIGHTS)}
                #{Stance (19) [B:PRO] TRADITION (ISSUE:WOMENS-RIGHTS)})
Norm:          (PRO C ISSUE:ISSUE.818 WOMENS-RIGHTS)
Status:        Active
Date-Open:     Sunday, January 22, 1989
Symbol:        ISSUE.818
The citizenry approves of women's civil rights.  
Support of women's civil rights upholds the belief in fairness
in society, a woman's right to have an abortion, the principle
of equality, the belief in a right to privacy, and the principle
of progress and change in society.  
Opposition to women's rights is important for tradition and preserving
the status quo.  Opposition to women's rights is consistent with
traditional family values.  
....ISSUE> cd group

....GROUP> help
HELP           print help information
?                         print command names
ACTIVE UNDELETE UNDEL     change status to active
ADD A                     add an item
ALIAS                     create a command synonym
AND                       selection conjunction
APPEND APP                append to field
COMPILE                   compile data file
COMPILE-DATE              date of last compilation
COMPLETED COMPLETE        flag current item as completed
COPY CP                   copy an entry
DELETE DEL                delete current item
DISPLAY DIS D             display current item
EDIT ED E                 edit a field
EXIT X                    save current updates and exit
EXPUNGE EXP               remove deleted items
GET G                     get old db
HEADERS HEADER HEAD H LS  print item headers
LOCK                      flag current item as locked
PENDING PEND P            change status to pending
PRINT                     print current db to file
PRINT-DATE                date of last printing
QUIT BYE Q                exit without saving current updates
SAVE S                    save current updates
SHOW-UPDATES UPDATES      show updated items
SORT                      sort items
SYN INDEX                 create an index synonym
CDB CD                    change to parent/child db
MKDB                      make child db at current item
MOVE MV                   move current item to given db
UNDO U                    undo last command
NOTES NOTE                update the Notes field
NAME                      update the Name field
SHORT ENGLISH-SHORT       update the English-Short field
ENGLISH ENG               update the English field
PRO-ENGLISH PRO-E         update the Pro-English field
CON-ENGLISH CON-E         update the Con-English field
FRENCH                    update the French field
FRENCH-SHORT              update the French-Short field
PRO-FRENCH PRO-F          update the Pro-French field
CON-FRENCH CON-F          update the Con-French field
NORM NORMS                update the Norm field
SYNONYMS SYNONYM NAMES    update the Synonyms field
STANCE-SORT-KEY           update the Stance-Sort-Key field
KEYWORDS KEYS KEY         update the Keywords field
ISA                       update the Isa field
NUMBER                    update the Number field
GENDER                    update the Gender field
ISSUES ISSUE              update the Issues field
STANCES STANCE            update the Stances field
DATE-CLOSED CLOSED        update the Date-Closed field
DATE-OPEN OPEN            update the Date-Open field
REMARKS TEXT              update the Remarks field
STATUS ST                 update the Status field
SUBJECT SUBJ              update the Subject field
KEYWORDS KEYS             update the Keywords field
DB                        update the Db field

aliases:
AS                  APPEND STANCES 
HC                  HEADERS CURRENT 
N                   STANCES 
....GROUP> headers

      0   AFL-CIO                                 (AFLCIO)
      1   Aerospace Industry                      (AEROSPACE)
      2   Agriculture Industry                    (AGRICULTURE)
      3   Airline Industry                        (AIRLINES)
      4   American Civil Liberties Union          (ACLU)
      5   American Conservative Union             (ACU)
      6   American Legion                         (AMERICAN-LEGION)
      7   Americans for Constitutional Action     (ACA)
      8   Americans for Democratic Action         (ADA)
      9   Amnesty International                   (AMNESTY-INTERNATIONAL)
      10  Asians                                  
      11  Automotive Industry                     (CARS AUTOMOBILE AUTOMOTIVE
                                                   AUTO)
      12  Banking                                 (BANKERS)
      13  Blacks                                  
      14  Business                                (INDUSTRY COMPANIES)
      15  Catholics                               
      16  Central Intelligence Agency             (CIA)
      17  Chamber of Commerce of the United States (COC)
      18  Christians                              
      19  Cigar Association of America            (CIGAR-ASSOCIATION)
      20  Coal Industry                           (COAL)
      21  Committee on Political Education of the AFL-CIO (COPE)
      22  Common Cause                            (COMMON-CAUSE)
      23  Communist Party                         (COMMUNISTS)
      24  Competitive Enterprise Institute        (CEI)
      25  Consumer Federation of America          (CFA)
      26  Consumers                               (CONSUMER)
      27  Country                                 (COUNTRY US)
      28  Defense Contractors                     (DEFENSE-CONTRACTORS)
      29  Defense Industry                        (DEFENSE DEFENSE-INDUSTRY)
      30  Democrats                               
      31  Doves                                   
      32  Elderly                                 (AGED OLD)
      33  Environmental Defense Fund              (ENVIRONMENTAL-DEFENSE-FUND)
      34  Environmental Protection Agency         (EPA)
      35  Ethnic                                  
      36  Evangelicals                            
      37  Farming                                 
      38  Fishing Industry                        (FISHING)
      39  Foreign Groups                          (FOREIGN)
      40  Friends                                 (FRIEND)
      41  Gays                                    (LESBIANS HOMOSEXUALS)
      42  Generic Group                           (GROUP)
      43  Handicapped                             
      44  Hawks                                   
      45  Hispanics                               
      46  House Administration Committee          (HOUSE-ADMINISTRATION)
      47  House Agriculture Committee             (HOUSE-AGRICULTURE)
      48  House Appropriations Committee          (HOUSE-APPROPRIATIONS)
      49  House Armed Services Committee          (HOUSE-ARMED-SERVICES)
      50  House Banking, Finance, and Urban Affairs (HOUSE-BANKING)
      51  House Budget Committee                  (HOUSE-BUDGET)
      52  House Democratic Caucus                 (HOUSE-DEMOCRATIC-CAUCUS)
      53  House District of Columbia Committee    (HOUSE-DC)
      54  House Education and Labor Committee     (HOUSE-EDUCATION)
      55  House Energy and Commerce Committee     (HOUSE-ENERGY)
      56  House Foreign Affairs Committee         (HOUSE-FOREIGN)
      57  House Government Operations Committee   (HOUSE-GOVERNMENT-OPERATIONS)
      58  House Interior Committee                (HOUSE-INTERIOR)
      59  House Judiciary Committee               (HOUSE-JUDICIARY)
      60  House Majority Leader                   (HOUSE-MAJORITY-LEADER)
      61  House Majority Whip                     (HOUSE-MAJORITY-WHIP)
      62  House Merchant Marine and Fisheries Committee (HOUSE-MERCHANT-MARINE)
      63  House Minority Leader                   (HOUSE-MINORITY-LEADER)
      64  House Permanent Select Committee on Intelligence (HOUSE-INTELLIGENCE)
      65  House Public Works and Transportation   (HOUSE-PUBLIC-WORKS)
      66  House Republican Policy Caucus          (HOUSE-REPUBLICAN-CAUCUS)
      67  House Rules Committee                   (HOUSE-RULES)
      68  House Science Space and Technology Committee (HOUSE-SCIENCE)
      69  House Select Committee on Aging         (HOUSE-AGING)
      70  House Small Business Committee          (HOUSE-SMALL-BUSINESS)
      71  House Veterans Affairs Committee        (HOUSE-VETERANS-AFFAIRS)
      72  House Ways and Means Committee          (HOUSE-WAYS)
      73  Insurance Industry                      (INSURANCE)
      74  International Monetary Fund             (IMF)
      75  International Red Cross                 (RED-CROSS)
      76  Jews                                    (JEW JEWISH)
      77  Journalists                             
      78  Labor Unions                            (LABOR UNIONS UNION)
      79  League of Conservation Voters           (LCV)
      80  League of Women Voters                  (LWV)
      81  Legal Services                          (LEGAL-AID LEGAL-SERVICES)
      82  Lobbyist                                (LOBBY)
      83  Mining Industry                         (MINING MINERALS)
      84  Minority Groups                         (MINORITY)
      85  Municipal Officials                     (MUNICIPALITIES)
      86  National Association for the Advancement of Colored People (NAACP)
      87  National Education Association          (NEA)
      88  National Organization of Women          (NOW)
      89  National Rifle Association              (NRA)
      90  National Security Index of the American Security Council (NSI)
      91  National Taxpayers Union                (NTU)
      92  Native Americans                        (INDIANS)
      93  News Media                              (NEWS MEDIA)
      94  Newspaper Editors                       (EDITOR)
      95  Newspapers                              
      96  Occupational Health and Safety Administration (OSHA)
      97  Oil Industry                            (OIL)
      98  Opponents                               (OPPONENT OPPOSITION)
      99  Palestine Liberation Organization       (PLO)
      100  Party Activists                        (POL POLS)
      101  Political Contributors                 (CONTRIBUTORS)
      102  Political Party                        (PARTY)
      103  Radio                                  
      104  Ralph Nader                            (NADER)
      105  Relief Agency                          (RELIEF-AGENCY)
      106  Religious Organizations                (RELIGION)
      107  Republicans                            (GOP)
      108  Senate Agriculture, Nutrition, and Forestry Committee (SEN-AGRICULTURE)
      109  Senate Appropriations Committee        (SEN-APPROPRIATIONS)
      110  Senate Armed Services Committee        (SEN-ARMED-SERVICES)
      111  Senate Banking, Housing, and Urban Affairs Committee (SEN-BANKING)
      112  Senate Budget Committee                (SEN-BUDGET)
      113  Senate Commerce, Science, and Transportation Committee (SEN-COMMERCE)
      114  Senate Energy and Natural Resources Committee (SEN-ENERGY)
      115  Senate Environment and Public Works Committee (SEN-ENVIRONMENT)
      116  Senate Finance Committee               (SEN-FINANCE)
      117  Senate Foreign Relations Committee     (SEN-FOREIGN)
      118  Senate Governmental Affairs Committee  (SEN-GOVERNMENTAL)
      119  Senate Judiciary Committee             (SEN-JUDICIARY)
      120  Senate Labor and Human Resources Committee (SEN-LABOR)
      121  Senate Majority Leader                 (SENATE-MAJORITY-LEADER)
      122  Senate Majority Whip                   (SEN-MAJORITY-WHIP)
      123  Senate Minority Leader                 (SEN-MINORITY-LEADER)
      124  Senate Select Committee on Intelligence (SEN-INTELLIGENCE)
      125  Senate Veterans Affairs Committee      (SEN-VETERANS)
      126  Ship Building                          (SHIPS)
      127  Shipping Industry                      (SHIPPING)
      128  Shoe Industry                          (SHOE SHOES)
      129  Speaker of the House                   (SPEAKER)
      130  State and Local Government             (STATE-AND-LOCAL)
      131  Steel Industry                         (STEEL)
      132  Supporters                             (SUPPORTER)
      133  Teamsters                              
      134  Television                             (TV)
      135  The Committee for the Survival of a Free Congress (CSFC)
      136  Tobacco Industry                       (TOBACCO)
      137  UNITA                                  
      138  US Congress                            (CONGRESS)
      139  US Government                          (USA)
      140  US Government Agencies                 (US-AGENCY)
      141  US House of Representatives            (HOUSE)
      142  US Senate                              (SENATE)
      143  United Nations                         (UN)
      144  Veterans Groups                        (VETERAN VETERANS)
      145  Veterans of Foreign Wars               (VFW)
      146  Womens Groups                          (WOMEN)
  *   147  World Bank                             (WORLD-BANK)
....GROUP> hc

  *   147  World Bank                             (WORLD-BANK)
....GROUP> display

Name:          World Bank
Issues:        (THIRD-WORLD-DEBT)
English:       the World Bank
Synonyms:      (WORLD-BANK)
Status:        Active
Date-Open:     Sunday, April 16, 1989
Symbol:        GROUP.2584
I stress my long-standing support of the World Bank. (*)  
....GROUP> epa

Keyword index: EPA

  *   34  Environmental Protection Agency         (EPA)
....GROUP> display

Name:          Environmental Protection Agency
Issues:        (ENVIRONMENT)
English:       the Environmental Protection Agency
English-Short:  EPA
Synonyms:      (EPA)
Norm:          (PRO C GROUP:GROUP.3136 EPA)
Isa:           (US-AGENCY)
Status:        Active
Date-Open:     Monday, September 5, 1988
Symbol:        GROUP.3136
Most people support the Environmental Protection Agency.  
....GROUP> cd bill

....BILL> help
HELP            print help information
?                         print command names
ACTIVE UNDELETE UNDEL     change status to active
ADD A                     add an item
ALIAS                     create a command synonym
AND                       selection conjunction
APPEND APP                append to field
COMPILE                   compile data file
COMPILE-DATE              date of last compilation
COMPLETED COMPLETE        flag current item as completed
COPY CP                   copy an entry
DELETE DEL                delete current item
DISPLAY DIS D             display current item
EDIT ED E                 edit a field
EXIT X                    save current updates and exit
EXPUNGE EXP               remove deleted items
GET G                     get old db
HEADERS HEADER HEAD H LS  print item headers
LOCK                      flag current item as locked
PENDING PEND P            change status to pending
PRINT                     print current db to file
PRINT-DATE                date of last printing
QUIT BYE Q                exit without saving current updates
SAVE S                    save current updates
SHOW-UPDATES UPDATES      show updated items
SORT                      sort items
SYN INDEX                 create an index synonym
CDB CD                    change to parent/child db
MKDB                      make child db at current item
MOVE MV                   move current item to given db
UNDO U                    undo last command
NOTES NOTE                update the Notes field
NAME                      update the Name field
ENGLISH                   update the English field
FRENCH                    update the French field
NUMBER BNUMBER            update the Bnumber field
DATE-OF-VOTE VOTE-DATE    update the Date-Of-Vote field
PRES-POS                  update the Pres-Pos field
VOTE-TALLY TALLY VOTE     update the Vote-Tally field
TEST-BILL                 update the Test-Bill field
SESSION                   update the Session field
SYNONYMS SYNONYM NAMES    update the Synonyms field
ISA                       update the Isa field
MAJORITY-FACTOR MAJORITY FACTOR  update the Majority-Factor field
ISSUES ISSUE              update the Issues field
IMPORTANCE IMPORT         update the Importance field
FOR STANCE-FOR            update the Stance-For field
AGN STANCE-AGN            update the Stance-Agn field
INFER-STANCES I-STANCE-FOR  update the I-Stance-For field
DATE-CLOSED CLOSED        update the Date-Closed field
DATE-OPEN OPEN            update the Date-Open field
REMARKS TEXT              update the Remarks field
STATUS ST                 update the Status field
SUBJECT SUBJ              update the Subject field
KEYWORDS KEYS             update the Keywords field
DB                        update the Db field

aliases:
PP                  PRES-POS 
EDITC               EDIT STANCE-AGN 
EDITP               EDIT STANCE-FOR 
ACON                APPEND STANCE-AGN 
APRO                APPEND STANCE-FOR 
HC                  HEADER CURRENT 
HC                  HEADER CURRENT 
....BILL> headers

      0   HR-5142 100-2 [B]  AIDS Federal Policy / Recommittal
      1   HR-4868 99-2  [C]  Anti-Apartheid Act
      2   HJR-372 99-1  [B]  Balanced Budget and Emergency Deficit Control Act
      3   HR-3299 101-1 [B]  Capital Gains Reduction - 1989
      4   HR-3    101-2 [B]  Child Care
      5   S-557   100-2 [B]  Civil Rights Restoration Act/Passage
      6   HR-2342 100-1 [C]  Coast Guard Authorization / Reflagging Persian Gulf Ships
      7   HJR-484 100-2 [C]  Contra Aid / Passage
      8   X3      NIL   [C]  Death Penalty for Drug Dealers
      9   AMD     100   [C]  Defense Authorization, Fiscal 1988 / Chemical Weapons
      10  HR-5167 98-2  [C]  Defense Spare Parts Procurement Reform Act
      11  HR-4428 99-2  [B]  Department of Defense Authorization Act, Fiscal 1987
      12  HR-1524 99-2  [C]  Employee Polygraph Protection Act
      13  HR-5345 98-2  [C]  Equal Access Act
      14  HJR-1   98-1  [B]  Equal Rights Amendment to the US Constitution
      15  HR-1234 98-1  [C]  Fair Practices and Procedures in Automotive Products Act of 1983
      16  HR-4332 99-2  [C]  Federal Firearms Law Reform Act
      17  HJR-350 101-2 [C]  Flag Burning Constitutional Amendment
      18  HR-2978 101-1 [B]  Flag Desecration
      19  HR-2100 99-1  [B]  Food Security Act
      20  HR-7    101-1 [A]  Handgun Waiting Period
      21  HR-466  100-2 [C]  Home Health Care
      22  S-1200  99-2  [C]  Immigration Reform and Control Act
      23  HR-1510a 98-2 [C]  Immigration Reform and Control Act of 1983
      24  HR-1510 98-2  [C]  Immigration Reform and Control Act of 1983
      25  X1      NIL   [A]  Impeachment of Nixon
      26  HR-2760 98-1  [C]  Intelligence Authorization Act of Fiscal Year 1983
      27  HR-4759 99-2  [C]  Intelligence Authorization Act, Fiscal 1987
      28  HR-5119 98-2  [C]  International Security and Development Cooperation Act of 1984
  *   29  NIL     100-2 [B]  NIL
      30  NIL     98-2  [C]  NIL
      31  NIL     98-1  [C]  NIL
      32  HR-5210 100-2 [C]  Omnibus Drug Bill / Waiting Period for Handgun Purchases
      33  HR-4848 100-2 [C]  Omnibus Trade Bill
      34  S-2527  100-2 [B]  Plant Closing Layoff Notice Bill
      35  HJR-540 99-2  [B]  Resolution Concerning Funding for Nicaragua Democratic Resistance
      36  HJR-13  98-1  [C]  Resolution Concerning a Nuclear Freeze
      37  HR-1900 98-1  [B]  Social Security Amendments of 1983
      38  HR-4800 100-2 [C]  Space Station
      39  HR-4264 100-2 [B]  Star Wars
      40  HR-1183 98-1  [B]  Tax Rate Equity Act of 1983
      41  HR-3838 99-2  [B]  Tax Reform Act of 1986
      42  HR-1154 100-2 [C]  Textile and Apparel Trade Act / Veto Override
      43  HR-1562 99-2  [C]  Textile and Apparel Trade Enforcement Act
      44  HR-3191 98-1  [C]  Treasury, Postal Service and General Government Appropriations Act, 1984
      45  HR-8    99-1  [C]  Water Quality Renewal Act
....BILL> hc

  *   29  NIL     100-2 [B]  NIL
....BILL> flag

Unknown command.
....BILL> hr-2978

Keyword index: HR-2978

  *   18  HR-2978 101-1 [B]  Flag Desecration
....BILL> hc

  *   18  HR-2978 101-1 [B]  Flag Desecration
....BILL> display

Name:          Flag Desecration
English:       the flag desecration bill
French:        la loi de la profanation du drapeau
Bnumber:       HR-2978
Synonyms:      (FLAG-DESECRATION)
Date-Of-Vote:  Tuesday, September 12, 1989
Vote-Tally:    (PASSED 380 38 (R 151 21 D 229 17))
Pres-Pos:      FOR
Session:       101-1
Issues:        (FLAG-BURNING BILL-OF-RIGHTS FREE-SPEECH)
Importance:    B
Stance-For:    (#{Stance (20) [B:CON] FLAG-BURNING (BILL:HR-2978)}
                #{Stance (21) [B:PRO] PATRIOTISM (BILL:HR-2978)})
Stance-Agn:    (#{Stance (22) [B:PRO] FREE-SPEECH (BILL:HR-2978)})
Status:        Active
Date-Open:     Monday, January 29, 1990
Symbol:        BILL.155
Remarks:
Bill banning the desecration of the American flag.
Support of the flag desecration bill stands firmly against the
right of burning the American flag in protest.  Support of the
flag desecration bill upholds the belief in patriotism and devotion
to this country.  
Opposition to HR-2978 upholds the right of freedom of speech.  
....BILL> cd strategy

....STRATEGY> help
HELP        print help information
?                         print command names
ACTIVE UNDELETE UNDEL     change status to active
ADD A                     add an item
ALIAS                     create a command synonym
AND                       selection conjunction
APPEND APP                append to field
COMPILE                   compile data file
COMPILE-DATE              date of last compilation
COMPLETED COMPLETE        flag current item as completed
COPY CP                   copy an entry
DELETE DEL                delete current item
DISPLAY DIS D             display current item
EDIT ED E                 edit a field
EXIT X                    save current updates and exit
EXPUNGE EXP               remove deleted items
GET G                     get old db
HEADERS HEADER HEAD H LS  print item headers
LOCK                      flag current item as locked
PENDING PEND P            change status to pending
PRINT                     print current db to file
PRINT-DATE                date of last printing
QUIT BYE Q                exit without saving current updates
SAVE S                    save current updates
SHOW-UPDATES UPDATES      show updated items
SORT                      sort items
SYN INDEX                 create an index synonym
CDB CD                    change to parent/child db
MKDB                      make child db at current item
MOVE MV                   move current item to given db
UNDO U                    undo last command
QUOTE                     update the Quote field
NOTES NOTE                update the Notes field
NAME                      update the Name field
SYNONYMS SYNONYM NAMES    update the Synonyms field
TEST                      update the Test field
TEST-CODE CODE            update the Test-Code field
PROTOCOL                  update the Protocol field
PREAMBLE                  update the Preamble field
NO-SECOND-TRY NO-SECOND   update the No-Second-Try field
EXAMPLE                   update the Example field
RANK                      update the Rank field
ISA                       update the Isa field
POLARITY POLAR            update the Polarity field
DATE-CLOSED CLOSED        update the Date-Closed field
DATE-OPEN OPEN            update the Date-Open field
REMARKS TEXT              update the Remarks field
STATUS ST                 update the Status field
SUBJECT SUBJ              update the Subject field
KEYWORDS KEYS             update the Keywords field
DB                        update the Db field

aliases:
HC                  HEADER CURRENT 
PPP                 PREAMBLE 
....STRATEGY> headers

      0   NILPopular decision                     [A]  @@@(POPULAR)
      1   NILUnimportant Bill                     [B]  @@@(UNIMPORTANT-BILL)
      2   NILNon-partisan decision                [B]  @@@(NON-PARTISAN)
      3   NILNot constitutional                   [B]  @@@(NOT-CONSTITUTIONAL)
      4   NILBalance the books                    [C]  @@@(BALANCE-THE-BOOKS)
      5   NILMinimize adverse effects             [C]  @@@(MINIMIZE-ADVERSE-EFFECTS)
      6   NILInconsistent constituency            [C]  @@@(INCONSISTENT-CONSTITUENCY)
      7   NILSimple consensus                     [C]  @@@(SIMPLE-CONSENSUS)
      8   NILNot good enough                      [C]  @@@(NOT-GOOD-ENOUGH)
      9   NILBest for the country                 [C]  @@@(BEST-FOR-THE-COUNTRY)
      10  NILShifting alliances                   [C]  @@@(SHIFTING-ALLIANCES)
      11  NILPartisan Decision                    [C]  @@@(PARTISAN)
      12  NILNormative decision                   [D]  @@@(NORMATIVE)
      13  NILSimple Majority                      [D]  @@@(SIMPLE-MAJORITY
                                                           MAJORITY)
      14  NILDeeper analysis                      [E]  @  (DEEPER-ANALYSIS)
      15  NILNo decision                          [F]  @ @(NO-DECISION)
  *   16  NILUnpopular decision                   [X]   @@(UNPOPULAR)
      17  NILInoculation                          [X]  @@@(INOCULATION)
      18  NILChange of heart                      [X]  @@@(CHANGE-OF-HEART)
      19  NILMixed constituency                   [X]   @@(MIXED-CONSTITUENCY)
      20  NILTwo Minds                            [X]  @@@(TWO-MINDS)
      21  NILIt couldn't pass                     [X]  @@@(IT-COULD-NOT-PASS)
....STRATEGY> hc

  *   16  NILUnpopular decision                   [X]   @@(UNPOPULAR)
....STRATEGY> display

Name:          Unpopular decision
Synonyms:      (UNPOPULAR)
Quote:         I know people will criticize me for this vote, but I had to do it.
               I couldn't live with myself if I didn't.
               I have to use my judgment.  You can express an opinion.  I have to make a decision. [Trustee]
               I stand by my record.  I'm not going to change my principles.
               I hope you appreciate that and will look at my record as a whole.

Rank:          X
Test:          Major conflicts among stances.

Preamble:      PREAMBLE-UNPOPULAR
Protocol:      PROTOCOL-UNPOPULAR
No-Second-Try:  T
Status:        Active
Date-Open:     Sunday, April 16, 1989
Symbol:        STRATEGY.2682
Remarks:       Recognizes that vote will not play well with many constituents.
....STRATEGY> quit

END-OF-DBASE
* (vote 'udall 'hr-2978)

*********************************************************************************
* Decision:      @23                                                            *
* Member:        Morris K. Udall                                                *
* Bill:          Flag Desecration                                               *
* Bill banning the desecration of the American flag.                            *
*********************************************************************************

*********************************************************************************
*                        Analyzing alternative positions                        *
*********************************************************************************

*********************************************************************************
* Vote FOR HR-2978                                                              *
*********************************************************************************

Considering implications of vote FOR HR-2978
(#{Stance (24) [C:CON] FLAG-BURNING (GROUP:DEMOCRATS)})
*********************************************************************************
* Vote AGN HR-2978                                                              *
*********************************************************************************

Considering implications of vote AGN HR-2978
(#{Stance (25) [B:PRO] FREE-SPEECH (BILL:HJR-350)})
*********************************************************************************
*                         Applying decision strategies                          *
*********************************************************************************

*********************************************************************************
*                      Re-Analyzing alternative positions                       *
*********************************************************************************

*********************************************************************************
* Vote FOR HR-2978                                                              *
*********************************************************************************

Considering implications of vote FOR HR-2978
(#{Stance (24) [C:CON] FLAG-BURNING (GROUP:DEMOCRATS)})
*********************************************************************************
* Vote AGN HR-2978                                                              *
*********************************************************************************

Considering implications of vote AGN HR-2978
(#{Stance (25) [B:PRO] FREE-SPEECH (BILL:HJR-350)})
*********************************************************************************
*                      Re-Analyzing alternative positions                       *
*********************************************************************************

*********************************************************************************
* Vote FOR HR-2978                                                              *
*********************************************************************************

Considering implications of vote FOR HR-2978
(#{Stance (24) [C:CON] FLAG-BURNING (GROUP:DEMOCRATS)})
*********************************************************************************
* Vote AGN HR-2978                                                              *
*********************************************************************************

Considering implications of vote AGN HR-2978
(#{Stance (26) [A:PRO] CONSTITUTION (GROUP:ACLU)}
 #{Stance (27) [A:PRO] BILL-OF-RIGHTS (BILL:HJR-350)}
 #{Stance (25) [B:PRO] FREE-SPEECH (BILL:HJR-350)}
 #{Stance (28) [B:PRO] BILL-OF-RIGHTS (BILL:HR-4332)}
 #{Stance (29) [B:PRO] CONSTITUTION (BILL:HR-5345)}
 #{Stance (30) [B:PRO] CONSTITUTION (GROUP:COUNTRY)})(AGN
                                                      (#{Stance (26) [A:PRO] CONSTITUTION (GROUP:ACLU)}))(AGN
                                                                                                          (#{Stance (27) [A:PRO] BILL-OF-RIGHTS (BILL:HJR-350)}))(AGN
                                                                                                                                                                  (#{Stance (31) [B:PRO] FREE-SPEECH (ISSUE:ISSUE.1078)}))(#{Stance (26) [A:PRO] CONSTITUTION (GROUP:ACLU)}
                                                                                                                                                                                                                           #{Stance (27) [A:PRO] BILL-OF-RIGHTS (BILL:HJR-350)}
                                                                                                                                                                                                                           #{Stance (28) [B:PRO] BILL-OF-RIGHTS (BILL:HR-4332)}
                                                                                                                                                                                                                           #{Stance (29) [B:PRO] CONSTITUTION (BILL:HR-5345)}
                                                                                                                                                                                                                           #{Stance (30) [B:PRO] CONSTITUTION (GROUP:COUNTRY)})
*********************************************************************************
*                                 Decision @23                                  *
*********************************************************************************

Isa-Depth:     
Bill:          
Name:          Flag Desecration
English:       the flag desecration bill
French:        la loi de la profanation du drapeau
Bnumber:       HR-2978
Synonyms:      (FLAG-DESECRATION)
Date-Of-Vote:  Tuesday, September 12, 1989
Vote-Tally:    (PASSED 380 38 (R 151 21 D 229 17))
Pres-Pos:      FOR
Session:       101-1
Issues:        (FLAG-BURNING BILL-OF-RIGHTS FREE-SPEECH)
Importance:    B
Stance-For:    (#{Stance (20) [B:CON] FLAG-BURNING (BILL:HR-2978)}
                #{Stance (21) [B:PRO] PATRIOTISM (BILL:HR-2978)})
Stance-Agn:    (#{Stance (22) [B:PRO] FREE-SPEECH (BILL:HR-2978)})
Status:        Active
Date-Open:     Monday, January 29, 1990
Symbol:        BILL.155
Remarks:
Bill banning the desecration of the American flag.
Support of the flag desecration bill opposes the right of burning
the American flag in protest.  Support of the flag desecration
bill is important for the principle of patriotism and devotion
to this country.  
Opposition to HR-2978 is important for the right of freedom of
speech.  

Member:        
Name:          Morris K. Udall
Fname:         MORRIS
Lname:         UDALL
Votes:         ((DEFENSE-AUTHORIZATION FOR) (SPACE-STATION FOR)
                (CIVIL-RIGHTS-RESTORATION-ACT FOR) (REFLAGGING-SHIPS FOR)
                (HANDGUN-CONTROL AGN) (CONTRA-AID2 FOR) (STAR-WARS --)
                (HOME-HEALTH-CARE AGN) (AIDS AGN) (LIMIT-IMPORTS AGN)
                (CAP-TAX-CUT FOR) (EXTEND-SS-BENEFIT AGN)
                (ESTAB-DOM-CONTENT FOR) (BAR-IMM-AMNESTY AGN)
                (OK-SCHOOL-PRAY AGN) (LIMIT-ABORTIONS AGN) (APPROVE-ERA FOR)
                (PASS-IMM-REFORM AGN) (CANCEL-MX-MISSILE FOR)
                (HALT-AID-TO-CONTRAS FOR) (INCR-AID-TO-EL-SAL AGN)
                (SUPP-NUCLEAR-FREEZE FOR) (CAP-GAINS-CUT FOR)
                (LMT-CLN-WATER-ACT AGN) (RPL-TOBAC-SUB AGN)
                (GRM-RDMN-DEF-RED AGN) (BAN-POLYGRAPH FOR)
                (RETAIN-GUN-CONTROL AGN) (CONTRA-AID AGN) (LMT-TEXT-IMP FOR)
                (LIMIT-SDI FOR) (AID-ANGOLA-REB AGN) (TAX-REFORM FOR)
                (S-AFRICA-SANC FOR) (IMMIG-REFORM FOR) (CHILD-CARE FOR)
                (FLAG-BURNING AGN))
Stances:       (#{Stance (32) [B:CON] CHEMICAL-WEAPONS (BILL:AMD)}
                #{Stance (33) [C:PRO] ELDERLY (BILL:HR-4800)}
                #{Stance (34) [C:PRO] HANDICAPPED (BILL:HR-4800)}
                #{Stance (35) [C:PRO] HOMELESSNESS (BILL:HR-4800)}
                #{Stance (36) [C:PRO] URBAN-RENEWAL (BILL:HR-4800)}
                #{Stance (37) [B:PRO] CIVIL-RIGHTS (BILL:S-557)}
                #{Stance (38) [B:PRO] FAIRNESS (BILL:S-557)}
                #{Stance (39) [B:CON] AGE-DISCRIMINATION (BILL:S-557)}
                #{Stance (40) [B:PRO] EDUCATION-RIGHTS (BILL:S-557)}
                #{Stance (41) [B:CON] PERSIAN-GULF (BILL:HR-2342)}
                #{Stance (42) [B:PRO] NON-INVOLVEMENT (BILL:HR-2342)}
                #{Stance (43) [B:PRO] GUN-CONTROL (BILL:HR-5210)}
                #{Stance (44) [B:PRO] CRIME (BILL:HR-5210)}
                #{Stance (45) [B:PRO] COMPASSION (BILL:HJR-484)}
                #{Stance (46) [B:PRO] HUMANITARIANISM (BILL:HJR-484)}
                #{Stance (47) [B:PRO] END-OF-HOSTILITIES (BILL:HJR-484)}
                #{Stance (48) [C:CON] MILITARY-SOLUTION (BILL:HJR-484)}
                #{Stance (49) [B:CON] SPENDING (BILL:HR-466)}
                #{Stance (50) [B:CON] GAY-RIGHTS (BILL:HR-5142)}
                #{Stance (51) [B:CON] SPENDING (BILL:HR-5142)}
                #{Stance (52) [B:PRO] REAGAN (BILL:HR-1154)}
                #{Stance (53) [B:CON] TRADE-RESTRICTIONS (BILL:HR-1154)}
                #{Stance (54) [C:CON] TAXES (BILL:HR-1183)}
                #{Stance (55) [B:PRO] FAIRNESS (BILL:HR-1183)}
                #{Stance (56) [C:CON] SOCIAL-SECURITY (BILL:HR-1900)}
                #{Stance (57) [C:CON] TAXES (BILL:HR-1900)}
                #{Stance (58) [C:PRO] TRADE-DEFICIT (BILL:HR-1234)}
                #{Stance (59) [C:PRO] TRADE-RESTRICTIONS (BILL:HR-1234)}
                #{Stance (60) [C:PRO] LABOR (BILL:HR-1234)}
                #{Stance (61) [C:PRO] IMMIGRATION (BILL:HR-1510A)}
                #{Stance (62) [C:CON] PRAYER (BILL:HR-5345)}
                #{Stance (29) [B:PRO] CONSTITUTION (BILL:HR-5345)}
                #{Stance (63) [B:PRO] ABORTION (BILL:HR-3191)}
                #{Stance (64) [B:PRO] ERA (BILL:HJR-1)}
                #{Stance (65) [B:PRO] WOMENS-RIGHTS (BILL:HJR-1)}
                #{Stance (66) [B:PRO] FAIRNESS (BILL:HJR-1)}
                #{Stance (67) [B:PRO] EQUITY (BILL:HJR-1)}
                #{Stance (68) [B:CON] IMMIGRATION (BILL:HR-1510)}
                #{Stance (69) [B:CON] MX (BILL:HR-5167)}
                #{Stance (70) [C:CON] DEFENSE-SPENDING (BILL:HR-5167)}
                #{Stance (71) [B:CON] CONTRA-AID (BILL:HR-2760)}
                #{Stance (72) [B:CON] EL-SALVADOR (BILL:HR-5119)}
                #{Stance (73) [B:PRO] NUCLEAR-FREEZE (BILL:HJR-13)}
                #{Stance (74) [C:PRO] ARMS-CONTROL (BILL:HJR-13)}
                #{Stance (75) [B:CON] HELP-WEALTHY (BILL:HR-3299)}
                #{Stance (76) [C:PRO] TAXES (BILL:HR-3299)}
                #{Stance (77) [B:PRO] FISCAL-RESPONSIBILITY (BILL:HR-3299)}
                #{Stance (78) [B:PRO] CLEAN-WATER (BILL:HR-8)}
                #{Stance (79) [B:PRO] CLEAN-AIR (BILL:HR-8)}
                #{Stance (80) [B:PRO] TOBACCO-PRICE-SUPPORTS (BILL:HR-2100)}
                #{Stance (81) [B:PRO] SPENDING (BILL:HJR-372)}
                #{Stance (82) [B:PRO] PRIVACY (BILL:HR-1524)}
                #{Stance (83) [B:CON] GUN-CONTROL (BILL:HR-4332)}
                #{Stance (28) [B:PRO] BILL-OF-RIGHTS (BILL:HR-4332)}
                #{Stance (84) [B:CON] CONTRA-AID (BILL:HJR-540)}
                #{Stance (85) [B:PRO] TRADE-RESTRICTIONS (BILL:HR-1562)}
                #{Stance (86) [B:PRO] TEXTILE-INDUSTRY (BILL:HR-1562)}
                #{Stance (87) [B:CON] SDI (BILL:HR-4428)}
                #{Stance (88) [B:CON] ANGOLA-REBELS (BILL:HR-4759)}
                #{Stance (89) [B:PRO] HUMAN-RIGHTS (BILL:HR-4759)}
                #{Stance (90) [B:PRO] PEACE (BILL:HR-4759)}
                #{Stance (91) [B:PRO] DIPLOMACY (BILL:HR-4759)}
                #{Stance (92) [B:PRO] ISOLATIONISM (BILL:HR-4759)}
                #{Stance (93) [B:PRO] TAX-REFORM (BILL:HR-3838)}
                #{Stance (94) [B:CON] APARTHEID (BILL:HR-4868)}
                #{Stance (95) [B:PRO] IMMIGRATION-REFORM (BILL:S-1200)}
                #{Stance (96) [B:PRO] CHILD-CARE (BILL:HR-3)}
                #{Stance (97) [B:PRO] FAMILY (BILL:HR-3)}
                #{Stance (98) [C:PRO] EDUCATION (BILL:HR-3)}
                #{Stance (99) [C:PRO] LABOR (BILL:HR-3)}
                #{Stance (25) [B:PRO] FREE-SPEECH (BILL:HJR-350)}
                #{Stance (27) [A:PRO] BILL-OF-RIGHTS (BILL:HJR-350)})
Issues:        (PROGRESSIVE)
Relations:     (#{Relation (100) [B:PRO] ADA (MEMBER:MEMBER.1025)}
                #{Relation (101) [A:PRO] ACLU (MEMBER:MEMBER.1025)}
                #{Relation (102) [B:PRO] COPE (MEMBER:MEMBER.1025)}
                #{Relation (103) [C:PRO] LCV (MEMBER:MEMBER.1025)}
                #{Relation (104) [B:CON] ACU (MEMBER:MEMBER.1025)}
                #{Relation (105) [B:CON] NTU (MEMBER:MEMBER.1025)}
                #{Relation (106) [B:CON] NSI (MEMBER:MEMBER.1025)}
                #{Relation (107) [B:CON] COC (MEMBER:MEMBER.1025)}
                #{Relation (108) [B:CON] CEI (MEMBER:MEMBER.1025)}
                #{Relation (109) [C:PRO] DEMOCRATS (MEMBER:MEMBER.1025)}
                #{Relation (110) [C:CON] REPUBLICANS (MEMBER:MEMBER.1025)}
                #{Relation (111) [C:PRO] COUNTRY (MEMBER:MEMBER.1025)})
Pro-Rel-Stances:  (#{Stance (112) [B:CON] CONTRA-AID (GROUP:ADA)}
                   #{Stance (113) [B:CON] APARTHEID (GROUP:ADA)}
                   #{Stance (114) [B:PRO] ARMS-CONTROL (GROUP:ADA)}
                   #{Stance (115) [B:PRO] SOCIAL (GROUP:ADA)}
                   #{Stance (116) [B:CON] BORK (GROUP:ADA)}
                   #{Stance (117) [B:CON] CAPITAL-PUNISHMENT (GROUP:ADA)}
                   #{Stance (118) [B:PRO] CIVIL-RIGHTS (GROUP:ADA)}
                   #{Stance (119) [B:CON] CONSTRUCTIVE-ENGAGEMENT (GROUP:ADA)}
                   #{Stance (120) [B:CON] CREATIONISM (GROUP:ADA)}
                   #{Stance (121) [B:PRO] ERA (GROUP:ADA)}
                   #{Stance (122) [A:PRO] GUN-CONTROL (GROUP:ADA)}
                   #{Stance (123) [B:PRO] HOUSING (GROUP:ADA)}
                   #{Stance (124) [B:PRO] HUMAN-RIGHTS (GROUP:ADA)}
                   #{Stance (125) [B:PRO] LABOR (GROUP:ADA)}
                   #{Stance (126) [B:CON] MANION (GROUP:ADA)}
                   #{Stance (127) [B:PRO] NUCLEAR-FREEZE (GROUP:ADA)}
                   #{Stance (128) [B:PRO] OPEN-HOUSING (GROUP:ADA)}
                   #{Stance (129) [B:CON] RACISM (GROUP:ADA)}
                   #{Stance (130) [B:PRO] BUSSING (GROUP:ADA)}
                   #{Stance (131) [B:CON] SDI (GROUP:ADA)}
                   #{Stance (132) [B:PRO] URBAN (GROUP:ADA)}
                   #{Stance (133) [B:PRO] VOTING-RIGHTS (GROUP:ADA)}
                   #{Stance (134) [B:CON] WEAPONS (GROUP:ADA)}
                   #{Stance (135) [B:PRO] WOMENS-RIGHTS (GROUP:ADA)}
                   #{Stance (136) [C:PRO] ABORTION (GROUP:ADA)}
                   #{Stance (137) [C:CON] BALANCED-BUDGET (GROUP:ADA)}
                   #{Stance (138) [C:CON] MX (GROUP:ADA)}
                   #{Stance (139) [C:CON] B-1 (GROUP:ADA)}
                   #{Stance (140) [B:PRO] FOOD-STAMPS (GROUP:ADA)}
                   #{Stance (141) [B:CON] CLINCH-RIVER (GROUP:ADA)}
                   #{Stance (142) [B:PRO] CIVIL-LIBERTIES (GROUP:ACLU)}
                   #{Stance (143) [B:PRO] PRIVACY (GROUP:ACLU)}
                   #{Stance (144) [C:PRO] LEGAL-SERVICES (GROUP:ACLU)}
                   #{Stance (145) [C:PRO] VOTING-RIGHTS (GROUP:ACLU)}
                   #{Stance (146) [C:CON] PRAYER (GROUP:ACLU)}
                   #{Stance (26) [A:PRO] CONSTITUTION (GROUP:ACLU)}
                   #{Stance (147) [B:PRO] LABOR (GROUP:COPE)}
                   #{Stance (148) [B:PRO] PLANT-CLOSING (GROUP:COPE)}
                   #{Stance (149) [B:PRO] CHILD-CARE (GROUP:COPE)}
                   #{Stance (150) [B:PRO] SPENDING (GROUP:COPE)}
                   #{Stance (151) [B:CON] BORK (GROUP:COPE)}
                   #{Stance (152) [B:PRO] SOCIAL (GROUP:COPE)}
                   #{Stance (153) [B:PRO] TRADE-RESTRICTIONS (GROUP:COPE)}
                   #{Stance (154) [C:PRO] VOTING-RIGHTS (GROUP:COPE)}
                   #{Stance (155) [C:CON] BALANCED-BUDGET (GROUP:COPE)}
                   #{Stance (156) [B:PRO] FOOD-STAMPS (GROUP:COPE)}
                   #{Stance (157) [B:PRO] ENERGY (GROUP:LCV)}
                   #{Stance (158) [B:PRO] ENVIRONMENT (GROUP:LCV)}
                   #{Stance (159) [B:PRO] CLEAN-WATER (GROUP:LCV)}
                   #{Stance (160) [B:PRO] CLEAN-AIR (GROUP:LCV)}
                   #{Stance (161) [B:PRO] SUPERFUND (GROUP:LCV)}
                   #{Stance (162) [B:CON] CLINCH-RIVER (GROUP:LCV)}
                   #{Stance (163) [B:PRO] AFFIRMATIVE-ACTION (GROUP:DEMOCRATS)}
                   #{Stance (164) [B:PRO] FARM (GROUP:DEMOCRATS)}
                   #{Stance (165) [B:CON] CONTRA-AID (GROUP:DEMOCRATS)}
                   #{Stance (166) [B:PRO] AIR-POLLUTION-CONTROL (GROUP:DEMOCRATS)}
                   #{Stance (167) [B:CON] ANTI-SEMITISM (GROUP:DEMOCRATS)}
                   #{Stance (168) [B:CON] APARTHEID (GROUP:DEMOCRATS)}
                   #{Stance (169) [B:PRO] ARMS-CONTROL (GROUP:DEMOCRATS)}
                   #{Stance (170) [B:CON] BORK (GROUP:DEMOCRATS)}
                   #{Stance (171) [B:CON] TOWER (GROUP:DEMOCRATS)}
                   #{Stance (172) [B:PRO] CHILD-CARE (GROUP:DEMOCRATS)}
                   #{Stance (173) [B:PRO] CIVIL-RIGHTS (GROUP:DEMOCRATS)}
                   #{Stance (174) [B:CON] CONSTRUCTIVE-ENGAGEMENT (GROUP:DEMOCRATS)}
                   #{Stance (175) [B:PRO] DOMESTIC (GROUP:DEMOCRATS)}
                   #{Stance (176) [B:PRO] ERA (GROUP:DEMOCRATS)}
                   #{Stance (177) [B:PRO] LABOR (GROUP:DEMOCRATS)}
                   #{Stance (178) [B:CON] MANION (GROUP:DEMOCRATS)}
                   #{Stance (179) [B:PRO] OPEN-HOUSING (GROUP:DEMOCRATS)}
                   #{Stance (180) [B:PRO] PLANT-CLOSING (GROUP:DEMOCRATS)}
                   #{Stance (181) [B:PRO] PUBLIC-WORKS (GROUP:DEMOCRATS)}
                   #{Stance (182) [B:PRO] RURAL-ELECTRIC (GROUP:DEMOCRATS)}
                   #{Stance (183) [B:PRO] DESEGREGATION (GROUP:DEMOCRATS)}
                   #{Stance (184) [B:PRO] SOCIAL-SECURITY (GROUP:DEMOCRATS)}
                   #{Stance (185) [B:PRO] TAX-REFORM (GROUP:DEMOCRATS)}
                   #{Stance (186) [B:PRO] URBAN (GROUP:DEMOCRATS)}
                   #{Stance (187) [B:PRO] VOTING-RIGHTS (GROUP:DEMOCRATS)}
                   #{Stance (188) [B:PRO] WATER-POLLUTION-CONTROL (GROUP:DEMOCRATS)}
                   #{Stance (189) [B:PRO] WOMENS-RIGHTS (GROUP:DEMOCRATS)}
                   #{Stance (190) [B:PRO] WHISTLE-BLOWERS (GROUP:DEMOCRATS)}
                   #{Stance (191) [C:PRO] DEATH-PENALTY (GROUP:DEMOCRATS)}
                   #{Stance (24) [C:CON] FLAG-BURNING (GROUP:DEMOCRATS)}
                   #{Stance (192) [C:CON] SDI (GROUP:DEMOCRATS)}
                   #{Stance (193) [C:PRO] JOB-PROTECTION (GROUP:DEMOCRATS)}
                   #{Stance (194) [B:PRO] ARMS-CONTROL (GROUP:COUNTRY)}
                   #{Stance (195) [C:PRO] BALANCED-BUDGET (GROUP:COUNTRY)}
                   #{Stance (196) [C:PRO] INDUSTRY (GROUP:COUNTRY)}
                   #{Stance (197) [C:PRO] CHILD-CARE (GROUP:COUNTRY)}
                   #{Stance (198) [C:PRO] CIVIL-LIBERTIES (GROUP:COUNTRY)}
                   #{Stance (199) [C:PRO] CIVIL-RIGHTS (GROUP:COUNTRY)}
                   #{Stance (30) [B:PRO] CONSTITUTION (GROUP:COUNTRY)}
                   #{Stance (200) [C:PRO] CONVENTIONAL-DEFENSE (GROUP:COUNTRY)}
                   #{Stance (201) [C:PRO] DEFENSE (GROUP:COUNTRY)}
                   #{Stance (202) [C:CON] DEFICIT (GROUP:COUNTRY)}
                   #{Stance (203) [B:PRO] DEMOCRACY (GROUP:COUNTRY)}
                   #{Stance (204) [C:PRO] ENERGY (GROUP:COUNTRY)}
                   #{Stance (205) [B:PRO] EQUALITY (GROUP:COUNTRY)}
                   #{Stance (206) [B:PRO] FAIRNESS (GROUP:COUNTRY)}
                   #{Stance (207) [C:PRO] FREE-ENTERPRISE (GROUP:COUNTRY)}
                   #{Stance (208) [B:PRO] FREEDOM (GROUP:COUNTRY)}
                   #{Stance (209) [C:PRO] JOBS (GROUP:COUNTRY)}
                   #{Stance (210) [B:PRO] HEALTH (GROUP:COUNTRY)}
                   #{Stance (211) [C:PRO] HOUSING (GROUP:COUNTRY)}
                   #{Stance (212) [C:PRO] HUMAN-RIGHTS (GROUP:COUNTRY)}
                   #{Stance (213) [C:PRO] INFLATION (GROUP:COUNTRY)}
                   #{Stance (214) [C:PRO] JUSTICE (GROUP:COUNTRY)}
                   #{Stance (215) [C:PRO] LAW-AND-ORDER (GROUP:COUNTRY)}
                   #{Stance (216) [C:PRO] EDUCATION-RIGHTS (GROUP:COUNTRY)}
                   #{Stance (217) [C:PRO] SOCIAL-SECURITY (GROUP:COUNTRY)}
                   #{Stance (218) [C:PRO] UNEMPLOYMENT-INSURANCE (GROUP:COUNTRY)}
                   #{Stance (219) [B:PRO] VOTING-RIGHTS (GROUP:COUNTRY)}
                   #{Stance (220) [C:PRO] WOMENS-RIGHTS (GROUP:COUNTRY)}
                   #{Stance (221) [C:PRO] FUTURE (GROUP:COUNTRY)})
Con-Rel-Stances:  (#{Stance (222) [B:PRO] CONTRA-AID (GROUP:ACU)}
                   #{Stance (223) [B:PRO] DEFENSE (GROUP:ACU)}
                   #{Stance (224) [B:PRO] BALANCED-BUDGET (GROUP:ACU)}
                   #{Stance (225) [B:PRO] BORK (GROUP:ACU)}
                   #{Stance (226) [B:CON] ERA (GROUP:ACU)}
                   #{Stance (227) [B:CON] GUN-CONTROL (GROUP:ACU)}
                   #{Stance (228) [C:CON] LABOR (GROUP:ACU)}
                   #{Stance (229) [B:PRO] MANION (GROUP:ACU)}
                   #{Stance (230) [B:CON] PLANT-CLOSING (GROUP:ACU)}
                   #{Stance (231) [B:CON] BUSSING (GROUP:ACU)}
                   #{Stance (232) [B:CON] SOCIAL (GROUP:ACU)}
                   #{Stance (233) [B:PRO] SDI (GROUP:ACU)}
                   #{Stance (234) [B:CON] VOTING-RIGHTS (GROUP:ACU)}
                   #{Stance (235) [B:CON] WOMENS-RIGHTS (GROUP:ACU)}
                   #{Stance (236) [B:CON] TAXES (GROUP:NTU)}
                   #{Stance (237) [B:PRO] TAX-REFORM (GROUP:NTU)}
                   #{Stance (238) [B:PRO] DEFENSE (GROUP:NSI)}
                   #{Stance (239) [B:PRO] MX (GROUP:NSI)}
                   #{Stance (240) [B:PRO] B-1 (GROUP:NSI)}
                   #{Stance (241) [B:PRO] EL-SALVADOR (GROUP:NSI)}
                   #{Stance (242) [C:CON] NUCLEAR-FREEZE (GROUP:NSI)}
                   #{Stance (243) [B:CON] TAXES (GROUP:COC)}
                   #{Stance (244) [B:PRO] DEREGULATION (GROUP:COC)}
                   #{Stance (245) [B:CON] SPENDING (GROUP:COC)}
                   #{Stance (246) [B:PRO] BALANCED-BUDGET (GROUP:COC)}
                   #{Stance (247) [B:CON] PLANT-CLOSING (GROUP:COC)}
                   #{Stance (248) [B:CON] LABOR (GROUP:COC)}
                   #{Stance (249) [B:PRO] CLINCH-RIVER (GROUP:COC)}
                   #{Stance (250) [B:PRO] DEREGULATION (GROUP:CEI)}
                   #{Stance (251) [B:PRO] FREE-ENTERPRISE (GROUP:CEI)}
                   #{Stance (252) [B:PRO] PRIVATIZATION (GROUP:CEI)}
                   #{Stance (253) [B:CON] ABORTION (GROUP:REPUBLICANS)}
                   #{Stance (254) [B:PRO] CONTRA-AID (GROUP:REPUBLICANS)}
                   #{Stance (255) [B:PRO] BORK (GROUP:REPUBLICANS)}
                   #{Stance (256) [B:PRO] VETERANS (GROUP:REPUBLICANS)}
                   #{Stance (257) [B:CON] CENTRAL-AMERICAN-PEACE-PLAN (GROUP:REPUBLICANS)}
                   #{Stance (258) [B:CON] COMMUNISM (GROUP:REPUBLICANS)}
                   #{Stance (259) [B:PRO] CONSTRUCTIVE-ENGAGEMENT (GROUP:REPUBLICANS)}
                   #{Stance (260) [B:PRO] DEFENSE (GROUP:REPUBLICANS)}
                   #{Stance (261) [B:PRO] DEREGULATION (GROUP:REPUBLICANS)}
                   #{Stance (262) [B:PRO] DRUGS (GROUP:REPUBLICANS)}
                   #{Stance (263) [B:CON] ERA (GROUP:REPUBLICANS)}
                   #{Stance (264) [B:CON] GUN-CONTROL (GROUP:REPUBLICANS)}
                   #{Stance (265) [B:CON] NUCLEAR-FREEZE (GROUP:REPUBLICANS)}
                   #{Stance (266) [B:PRO] PATRIOTISM (GROUP:REPUBLICANS)}
                   #{Stance (267) [B:CON] PLANT-CLOSING (GROUP:REPUBLICANS)}
                   #{Stance (268) [B:PRO] PLEDGE (GROUP:REPUBLICANS)}
                   #{Stance (269) [B:CON] FURLOUGHS (GROUP:REPUBLICANS)}
                   #{Stance (270) [B:PRO] PRAYER (GROUP:REPUBLICANS)}
                   #{Stance (271) [B:CON] TAXES (GROUP:REPUBLICANS)}
                   #{Stance (272) [B:PRO] TOWER (GROUP:REPUBLICANS)}
                   #{Stance (273) [C:PRO] FISCAL-RESPONSIBILITY (GROUP:REPUBLICANS)}
                   #{Stance (274) [C:CON] GAY-RIGHTS (GROUP:REPUBLICANS)}
                   #{Stance (275) [B:PRO] SPUR-INVESTMENT (GROUP:REPUBLICANS)}
                   #{Stance (276) [C:PRO] CAPITAL-GAINS-TAX-CUT (GROUP:REPUBLICANS)})
District:      AZ-2
Term-Start:    1961
Term-End:      1991
Party:         DEM
Committees:    (HOUSE-FOREIGN)
Status:        Active
Date-Open:     Tuesday, September 19, 1989
Symbol:        MEMBER.1025
Morris K. Udall emphasizes his deep-rooted support of the ACLU
s strong defense of the Bill of Rights.  He feels strongly in
favor of the ADA as a proponent of basic American values, in addition
to the progressive agenda of COPE.  He is strongly opposed to
the narrow special interest of the Chamber of Commerce, the National
Taxpayers Union, the NSI as an example of the radical right, the
ACU's right-wing reactionism, and the CEI business special interest
lobby.  Udall is for members of the Democratic party, the League
of Conservation Voters, and the country as a whole.  Udall is
opposed to Republicans.  

For-Stances:   (#{Stance (24) [C:CON] FLAG-BURNING (GROUP:DEMOCRATS)})
Agn-Stances:   (#{Stance (26) [A:PRO] CONSTITUTION (GROUP:ACLU)}
                #{Stance (27) [A:PRO] BILL-OF-RIGHTS (BILL:HJR-350)}
                #{Stance (25) [B:PRO] FREE-SPEECH (BILL:HJR-350)}
                #{Stance (28) [B:PRO] BILL-OF-RIGHTS (BILL:HR-4332)}
                #{Stance (29) [B:PRO] CONSTITUTION (BILL:HR-5345)}
                #{Stance (30) [B:PRO] CONSTITUTION (GROUP:COUNTRY)})
Number-For:    1
Number-Agn:    6
Group-For:     (#{Stance (24) [C:CON] FLAG-BURNING (GROUP:DEMOCRATS)})
Group-Agn:     (#{Stance (26) [A:PRO] CONSTITUTION (GROUP:ACLU)}
                #{Stance (30) [B:PRO] CONSTITUTION (GROUP:COUNTRY)})
For-Norms:     (#{Stance (277) [C:CON] FLAG-BURNING (ISSUE:ISSUE.1077)})
Agn-Norms:     (#{Stance (31) [B:PRO] FREE-SPEECH (ISSUE:ISSUE.1078)}
                #{Stance (278) [B:PRO] CONSTITUTION (ISSUE:ISSUE.2591)})
For-Bnorms:    (#{Stance (277) [C:CON] FLAG-BURNING (ISSUE:ISSUE.1077)}
                #{Stance (279) [B:PRO] PATRIOTISM (ISSUE:ISSUE.3822)})
Agn-Bnorms:    (#{Stance (31) [B:PRO] FREE-SPEECH (ISSUE:ISSUE.1078)}
                #{Stance (280) [A:PRO] RELIGION (ISSUE:ISSUE.24)}
                #{Stance (278) [B:PRO] CONSTITUTION (ISSUE:ISSUE.2591)})
Mi-Stance:     (AGN (#{Stance (26) [A:PRO] CONSTITUTION (GROUP:ACLU)}))
Mi-Group:      (AGN (#{Stance (26) [A:PRO] CONSTITUTION (GROUP:ACLU)}))
Mi-Record:     (AGN (#{Stance (27) [A:PRO] BILL-OF-RIGHTS (BILL:HJR-350)}))
Mi-Norm:       (AGN (#{Stance (31) [B:PRO] FREE-SPEECH (ISSUE:ISSUE.1078)}))
Strategy:      
Name:          Not constitutional
Synonyms:      (NOT-CONSTITUTIONAL)
Rank:          B
Test:          There is a consensus opposing the measure.  One issue among the
               opposing stances is the Constitution.

Test-Code:     #<FUNCTION STRAT-NOT-CONSTITUTIONAL>
Preamble:      PREAMBLE-NOT-CONSTITUTIONAL
Protocol:      PROTOCOL-NOT-CONSTITUTIONAL
Status:        Active
Date-Open:     Monday, April 24, 1989
Symbol:        STRATEGY.1344
Remarks:       Vote against a measure that would be struck down by 
               the Supreme Court.

Result:        AGN
Reason:        ((((#{Stance (26) [A:PRO] CONSTITUTION (GROUP:ACLU)}
                   #{Stance (27) [A:PRO] BILL-OF-RIGHTS (BILL:HJR-350)}
                   #{Stance (28) [B:PRO] BILL-OF-RIGHTS (BILL:HR-4332)}
                   #{Stance (29) [B:PRO] CONSTITUTION (BILL:HR-5345)}
                   #{Stance (30) [B:PRO] CONSTITUTION (GROUP:COUNTRY)})))
                (((#{Stance (25) [B:PRO] FREE-SPEECH (BILL:HJR-350)}))))
Downside:      ((((#{Stance (24) [C:CON] FLAG-BURNING (GROUP:DEMOCRATS)}))))
Deeper-Analysis:  B
Status:        Active
*********************************************************************************
* English rationale:                                                            *
*********************************************************************************
Morris K. Udall votes against bill HR-2978, the flag desecration
bill.  
After careful analysis, he believes that provisions of this bill
are not constitutional.  
He completely supports the belief in the United States Constitution
and the Bill of Rights.  Udall is eager to show his support for
the right of freedom of speech.  
But, Udall understands that members of the Democratic party oppose
the right of burning the American flag in protest.  

*********************************************************************************
*                              End of Decision @23                              *
*********************************************************************************
#{Decision (23) [AGN:HR-2978] Udall (DEM : AZ-2)B}
* 